import builder from "xmlbuilder2";

export interface PagoProveedoresSchema {
  id: number;
}

// prettier-ignore
export const xml_pago_proveedores = (data: PagoProveedoresSchema): string => {
  const doc= builder
    .create()
      .ele('Document')
        .ele('CstmrCdtTrfInitn')
          .ele('GrpHdr')
            .ele('MsgId').txt("Archivo141").up()
            .ele('CreDtTm').txt("2023-10-10T12:00:00").up()
            .ele('Authstn').up()
            .ele('NbOfTxs').txt("da").up()
            .ele('CtrlSum').up()
            .ele('InitgPty')
              .ele('Nm').txt('Nombre').up()
              .ele('PstlAdr').up()
              .ele('Id')
                .ele('OrgId')
                  .ele('AnyBIC').up()
                  .ele('LEI').up()
                  .ele('Othr')
                    .ele('Id').up()
                    .ele('SchmeNm').up()
                  .up()
                  .ele('Issr').up()
                .up()
                .ele('PrvtId').up()
              .up()
              .ele('CtryOfRes').up()
              .ele('CtcDtls').up()
            .up()
            .ele('FwdgAgt').up()
          .up()
          .ele('PmtInf')
            .ele('PmtInfId').txt('nombre archivo').up()
            .ele('PmtMtd').txt('TRF').up()
            .ele('BtchBookg').up()
            .ele('NbOfTxs').txt('transacciones').up()
            .ele('CtrlSum').up()
            .ele('PmtTpInf')
              .ele('InstrPrty').up()
              .ele('LclInstrm').up()
              .ele('CtgyPurp')
                .ele('Cd').txt('TRAN').up()
                .ele('Prtry').up()
              .up()
            .up()
            .ele('ReqdExctnDt')
              .ele('Dt').txt('dateprocesor').up()
              .ele('Dtm').up()
            .up()
            .ele('PoolgAdjstmntDt').up()
            .ele('Dbtr')
              .ele('Nm').txt('razon social').up()
              .ele('PstlAdr').up()
              .ele('Id')
                .ele('OrgId')
                  .ele('AnyBIC').up()
                  .ele('LEI').up()
                  .ele('Othr')
                    .ele('Id').txt('RUC').up()
                    .ele('SchmeNm').up()
                    .ele('Issr').up()
                  .up()
                .up()
                .ele('PrvtId').up()
              .up()
              .ele('CtryOfRes').up()
              .ele('CtctDtls').up()
            .up()
            .ele('DbtrAcct')
              .ele('Id')
                .ele('IBAN').up()
                .ele('Othr')
                  .ele('Id').txt('cc maestra').up()
                  .ele('SchmeNm').up()
                .up()
                .ele('Issr').up()
              .up()
              .ele('Tp')
                  .ele('Cd').up()
                  .ele('Prtry').up()
              .up()
              .ele('Ccy').txt('tipo mneda').up()
              .ele('Nm').up()
              .ele('Prxy').up()
            .up()
            .ele('DbtrAgt')
              .ele('FinInstnId')
                .ele('BICFI').up()
                .ele('ClrSysMmbId').up()
                .ele('LEI').up()
                .ele('Nm').up()
                .ele('PstlAdr').up()
                .ele('Othr')
                  .ele('Id').txt('Id cargo').up()
                  .ele('SchmeNm').up()
                  .ele('Issr').up()
                .up()
              .up()
            .up()
            .ele('DbtrAgtAcct').up()
            .ele('InstrForDbtrAgt').up()
            .ele('UltmtDbtr').up()
            .ele('ChrgBr').up()
            .ele('ChrgsAcct').up()
            .ele('ChrgsAcctAgt').up()
            .ele('CdtTrfTxInf')
              .ele('PmtId')
                .ele('InstrId').txt('id Bono').up()
                .ele('EndToEndId').txt('id bono').up()
                .ele('UETR').up()
              .up()
              .ele('PmtTpInf').up()
              .ele('Amt')
                .ele('InstdAmt').txt('bono').up()
                .ele('EqvtAmt').up()
              .up()
              .ele('XchgRateInf').up()
              .ele('ChrgBr').up()
              .ele('UltmtDbtr').up()
              .ele('IntrmyAgt1').up()
              .ele('IntrmyAgt1Acct').up()
              .ele('IntrmyAgt2').up()
              .ele('IntrmyAgt2Acct').up()
              .ele('IntrmyAgt3').up()
              .ele('IntrmyAgt3Acct').up()
              .ele('CdtrAgt').up()
              .ele('CdtrAgtAcct').up()
              .ele('Cdtr')
                .ele('Nm').txt('full name').up()
                .ele('PstlAdr').up()
                .ele('Id')
                  .ele('OrgId')
                    .ele('AnyBIC').up()
                    .ele('LEI').up()
                    .ele('Othr')
                      .ele('Id').up()
                      .ele('SchmeNm').up()
                      .ele('Issr').up()
                    .up()
                  .up()
                  .ele('PrvtId').up()
                .up()
                .ele('CtryOfRes').up()
                .ele('CtcDtls')
                  .ele('NmPrfx').up()
                  .ele('Nm').up()
                  .ele('PhneNb').up()
                  .ele('MobNb').up()
                  .ele('FaxNb').up()
                  .ele('EmailAdr').txt('b email').up()
                .up()
              .up()
              .ele('CdtrAcct')
                .ele('Id')
                  .ele('IBAN').up()
                  .ele('Othr')
                    .ele('Id').txt('numero de cuenta').up()
                    .ele('SchmeNm').up()
                    .ele('Issr').up()
                  .up()
                .up()
                .ele('Tp')
                  .ele('Cd').txt('tipo de cuenta').up()
                  .ele('Prtry').up()
                .up()
                .ele('Ccy').txt('PEN').up()
                .ele('Nm').up()
                .ele('Proxy').up()
              .up()
              .ele('UltmtCdtr').up()
              .ele('InstrForCdtrAgt').up()
              .ele('InstrForDbtrAgt').up()
              .ele('Purp').up()
              .ele('RgltryRptg').up()
              .ele('Tax').up()
              .ele('RltdRmtInf').up()
              .ele('RmtInf')
                .ele('Ustrd').txt('S//NINGUNO').up()
                .ele('Strd')
                  .ele('RfrdDocInf')
                    .ele('Tp')
                      .ele('CdOrPrtry')
                        .ele('Cd').up()
                        .ele('Prtry').up()
                      .up()
                      .ele('Issr').up()
                    .up()
                    .ele('Nb').up()
                    .ele('RltdDt').up()
                    .ele('LineDtls').up()
                  .up()
                  .ele('RfrdDocAmt')
                    .ele('DuePyblAmt').up()
                    .ele('DscntApldAmt').up()
                    .ele('CdtNoteAmt').up()
                    .ele('TaxAmt').up()
                    .ele('AdjstmntAmtAndRsn').up()
                    .ele('RmtdAmt').up()
                  .up()
                  .ele('CdtrRefInf').up()
                  .ele('Invcr').up()
                  .ele('Invcee').up()
                  .ele('TaxRmt').up()
                  .ele('GrnshmtRmt').up()
                  .ele('AddtlRmtInf').up()
                .up()
              .up()
              .ele('SplmtryData').up()
            .up()
          .up()
          .ele('SplmtryData').up()
        .up()
      .up()

  const xmlString=doc.end({prettyPrint: true})

  Deno.writeTextFile('./content.txt',xmlString)

  return xmlString;
};
