export const PATHS = {
  erp: {
    main: '/erp',
    auth: {
      main: '/erp/auth/login',
      otpLogin: '/erp/auth/otp-login',
    },
    modulos: {
      main: '/erp/modulos',
      home: '/erp/modulos/home',
      tiendas: {
        main: '/erp/modulos/tiendas',
        conciliar: '/erp/modulos/tiendas/conciliar',
        mediosPago: '/erp/modulos/tiendas/medios-pago',
        comprobarCajas: '/erp/modulos/tiendas/comprobar-cajas',
        generarAsientos: '/erp/modulos/tiendas/generar-asientos',
      },
      pagos: {
        main: '/erp/modulos/facturacionpagos',
        nuevoRequerimiento: '/erp/modulos/facturacionpagos/nuevorequerimiento',
        revisar: '/erp/modulos/facturacionpagos/revisar/:id',
        revisarNonDoc: '/erp/modulos/facturacionpagos/revisarnondoc/:id',
        listaEspera: '/erp/modulos/facturacionpagos/listaespera',
        programarPagos: {
          main: '/erp/modulos/facturacionpagos/programarpagos',
          crearOrden: '/erp/modulos/facturacionpagos/aprobarpagos/crearorden',
        },
        aprobarPagos: {
          main: '/erp/modulos/facturacionpagos/aprobarpagos',
          revisarOrden:
            '/erp/modulos/facturacionpagos/aprobarpagos/revisarorden/:id',
        },
        transferencia: '/erp/modulos/facturacionpagos/transferencia',
        anticipoGastos: '/erp/modulos/facturacionpagos/anticipogastos',
        consultaRequerimiento:
          '/erp/modulos/facturacionpagos/consultarequerimiento',
        reporteCaja: '/erp/modulos/facturacionpagos/reportecaja',
        avanzado: {
          main: '/erp/modulos/facturacionpagos/avanzado',
          config: '/erp/modulos/facturacionpagos/avanzado/config',
          seguridad: '/erp/modulos/facturacionpagos/avanzado/seguridad',
        },
        mantenimiento: {
          main: '/erp/modulos/facturacionpagos/mantenimiento',
          supplier: '/erp/modulos/facturacionpagos/mantenimiento/proveedor',
          cashbank: '/erp/modulos/facturacionpagos/mantenimiento/cajabanco',
          costCenter: '/erp/modulos/facturacionpagos/mantenimiento/centrocosto',
          category: '/erp/modulos/facturacionpagos/mantenimiento/categoria',
        },
      },
      requerimientos: {
        main: '/erp/modulos/requerimientos',
        solicitados: '/erp/modulos/requerimientos/solicitados',
        review: '/erp/modulos/requerimientos/requirement',
        reviewApproved: '/erp/modulos/requerimientos/review-approved',
        reviewRejected: '/erp/modulos/requerimientos/review-rejected',
        creation: '/erp/modulos/requerimientos/creation',
        aprobados: '/erp/modulos/requerimientos/aprobados',
        rechazados: '/erp/modulos/requerimientos/rechazados',
        mantenimiento: {
          supplier: '/erp/modulos/requerimientos/mantenimiento/proveedor',
          cashbank: '/erp/modulos/requerimientos/mantenimiento/caja-banco',
          costCenter: '/erp/modulos/requerimientos/mantenimiento/centro-costo',
          category: '/erp/modulos/requerimientos/mantenimiento/categoria',
          main: '/erp/modulos/requerimientos/mantenimiento',
        },
        reportes: {
          main: '/erp/modulos/requerimientos/reportes',
          cuentaCorriente:
            '/erp/modulos/requerimientos/reportes/cuenta-corriente',
          detallado: '/erp/modulos/requerimientos/reportes/detallado',
          resumido: '/erp/modulos/requerimientos/reportes/resumido',
          porCentroCosto:
            '/erp/modulos/requerimientos/reportes/por-centro-costo',
          porFecha: '/erp/modulos/requerimientos/reportes/por-fecha',
        },
      },
      digitalizacion: {
        main: '/erp/modulos/digitalizacion',
        documentos: '/erp/modulos/digitalizacion/documentos',
        escaneo: '/erp/modulos/digitalizacion/escaneo',
        metodosPagos: {
          main: '/erp/modulos/digitalizacion/metodos-pagos',
          izipay: '/erp/modulos/digitalizacion/metodos-pagos/izipay',
          culqui: '/erp/modulos/digitalizacion/metodos-pagos/culqui',
          bancos: '/erp/modulos/digitalizacion/metodos-pagos/bancos',
        },
      },
      mantenimiento: {
        main: '/erp/modulos/mantenimiento',
        categoria: '/erp/modulos/mantenimiento/categoria',
        cuentaCaja: '/erp/modulos/mantenimiento/cuenta-caja',
        centroCosto: '/erp/modulos/mantenimiento/centro-costo',
        tipoCuenta: '/erp/modulos/mantenimiento/tipo-cuenta',
        tipoCategoria: '/erp/modulos/mantenimiento/tipo-categoria',
        terminalPos: '/erp/modulos/mantenimiento/terminal-pos',
        motorizados: '/erp/modulos/mantenimiento/motorizados',
        menuReportes: '/erp/modulos/mantenimiento/menu-reportes',
        parametros: '/erp/modulos/mantenimiento/parametros',
      },
      seguridad: {
        main: '/erp/modulos/seguridad',
        usuarios: '/erp/modulos/seguridad/usuarios',
        roles: '/erp/modulos/seguridad/roles',
      },
      mercaderia: {
        main: '/erp/modulos/mercaderia',
        despachos: {
          main: '/erp/modulos/mercaderia/despachos',
          deAlmacen: '/erp/modulos/mercaderia/despachos/alamacen',
          entreTiendas: '/erp/modulos/mercaderia/despachos/entre-tiendas',
          porRuta: '/erp/modulos/mercaderia/despachos/por-ruta',
          consolidado: '/erp/modulos/mercaderia/despachos/consolidado',
        },
        divider: '/erp/modulos/mercaderia/divider',
        notaCredito: '/erp/modulos/mercaderia/nota-credito',
        compra: '/erp/modulos/mercaderia/compra',
        stockAlmacen: '/erp/modulos/mercaderia/stock-almacen',
        reportes: {
          main: '/erp/modulos/mercaderia/reportes',
          consultaDespachos:
            '/erp/modulos/mercaderia/reportes/consulta-despachos',
          porAlmacen: '/erp/modulos/mercaderia/reportes/por-almacen',
          ratio: '/erp/modulos/mercaderia/reportes/ratio',
        },
        kardex: '/erp/modulos/mercaderia/kardex',
        productos: '/erp/modulos/mercaderia/productos',
        items: '/erp/modulos/mercaderia/items',
        precios: '/erp/modulos/mercaderia/precios',
        almacenes: '/erp/modulos/mercaderia/almacen',
        proveedores: '/erp/modulos/mercaderia/proveedores',
        rutasDespacho: '/erp/modulos/mercaderia/rutas-despacho',
        transportistas: '/erp/modulos/mercaderia/transportistas',
        mantenimiento: {
          main: '/erp/modulos/mercaderia/mantenimiento',
          categorias: '/erp/modulos/mercaderia/mantenimiento/categorias',
          marcas: '/erp/modulos/mercaderia/mantenimiento/marcas',
          unidades: '/erp/modulos/mercaderia/mantenimiento/unidades',
          presentacion: '/erp/modulos/mercaderia/mantenimiento/presentacion',
          equivalencias: '/erp/modulos/mercaderia/mantenimiento/equivalencias',
          plantillas: '/erp/modulos/mercaderia/mantenimiento/plantillas',
        },
      },
      reportes: {
        main: '/erp/modulos/reportes',
      },
      recursosHumanos: {
        main: '/erp/modulos/recursos-humanos',
        empleado: '/erp/modulos/recursos-humanos/empleado',
        asistencia: '/erp/modulos/recursos-humanos/asistencia',
        cargos: '/erp/modulos/recursos-humanos/cargos',
        motorizados: '/erp/modulos/recursos-humanos/motorizados',
      },
    },
  },
}

export const PATHS_MAIN = [
  PATHS.erp.modulos.tiendas.main,
  PATHS.erp.modulos.requerimientos.main,
  PATHS.erp.modulos.digitalizacion.main,
  PATHS.erp.modulos.mantenimiento.main,
  PATHS.erp.modulos.mercaderia.main,
  PATHS.erp.modulos.reportes.main,
  PATHS.erp.modulos.recursosHumanos.main,
]
