version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  sftp:
    image: atmoz/sftp
    container_name: sftp_server
    ports:
      - "2222:22" # Puerto externo 2222 mapeado al puerto 22 del contenedor
    volumes:
      - ./sftp_data:/upload # Volumen local montado en el home del usuario
    environment:
      - SFTP_USERS=foo:pass:1001 # usuario:contraseña:uid
    restart: unless-stopped
volumes:
  redis_data:
    driver: local
