import { ItemRelation } from '../entities'

export const RELATIONS_ITEMS: ItemRelation[] = [
  {
    id: 152,
    name: 'ACEITUNA VERDE PORC 200 GR',
    price: 12,
    itemId: 55,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 1696,
    name: 'ACEITUNA VERDE PORC 300 GR',
    price: 12,
    itemId: 109,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 533,
    name: 'AJI PANCA SACHET BLS X 100 GR',
    price: 12,
    itemId: 56,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 163,
    name: 'ALBONDIGAS*200GR',
    price: 12,
    itemId: 30,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 1172,
    name: 'ALCOHOL GEL GALON',
    price: 12,
    itemId: 17,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 593,
    name: 'ASADO DE POLLO KILO',
    price: 12,
    itemId: 4,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 826,
    name: 'BANDEJA BIODEGRADABLE',
    price: 12,
    itemId: 79,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 708,
    name: 'BANDEJA PARA LASAGNA',
    price: 12,
    itemId: 80,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 277,
    name: 'BOLSA 03 X 06',
    price: 12,
    itemId: 94,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 283,
    name: 'BOLSA 10 X 15',
    price: 12,
    itemId: 95,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 285,
    name: 'BOLSA 12 X 16',
    price: 12,
    itemId: 96,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 286,
    name: 'BOLSA 14 X 20',
    price: 12,
    itemId: 97,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 287,
    name: 'BOLSA 16 X 19',
    price: 12,
    itemId: 98,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 476,
    name: 'BOLSA 18 X 26',
    price: 12,
    itemId: 99,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 291,
    name: 'BOLSA 20 X 30',
    price: 12,
    itemId: 100,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 709,
    name: 'BOLSA 20 X 30 ROJA',
    price: 12,
    itemId: 101,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 290,
    name: 'BOLSA 26 X 40',
    price: 12,
    itemId: 102,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 579,
    name: 'BOLSA PAPEL PAN AJO X 100 UND',
    price: 12,
    itemId: 89,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 447,
    name: 'CABANOSSI KILOS',
    price: 12,
    itemId: 5,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 609,
    name: 'CAJA FAMILIAR',
    price: 12,
    itemId: 50,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 601,
    name: 'CAJA GIGANTE',
    price: 12,
    itemId: 51,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 294,
    name: 'CAJA GRANDE',
    price: 12,
    itemId: 52,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 758,
    name: 'CAJA LARGE',
    price: 12,
    itemId: 53,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 1569,
    name: 'CAJA MEDIANA 22CM',
    price: 12,
    itemId: 54,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 448,
    name: 'CARNE PIZZERA KILO',
    price: 12,
    itemId: 6,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 110,
    name: 'CEBOLLA BLANCA KG',
    price: 12,
    itemId: 87,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 195,
    name: 'CEBOLLA BLANCA UND',
    price: 12,
    itemId: 36,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 650,
    name: 'CECINA PORX500GR',
    price: 12,
    itemId: 8,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 620,
    name: 'CHAMPIGNON LATA',
    price: 12,
    itemId: 48,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 588,
    name: 'CHANCHO AL CILINDRO X 500',
    price: 12,
    itemId: 7,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 776,
    name: 'CHOCLO DULCE DESGRANADO LATA',
    price: 12,
    itemId: 15,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 450,
    name: 'CHORIZO KILOS',
    price: 12,
    itemId: 9,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 522,
    name: 'CONTOMETRO SISTEMAS',
    price: 12,
    itemId: 81,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 759,
    name: 'CREMA DE AJO KILO',
    price: 12,
    itemId: 31,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 298,
    name: 'CUCHARITAS DESCARTABLES',
    price: 12,
    itemId: 103,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 300,
    name: 'DETERGENTE',
    price: 12,
    itemId: 58,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 301,
    name: 'ESCOBA',
    price: 12,
    itemId: 59,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 302,
    name: 'ESPONJA DE FIERRO',
    price: 12,
    itemId: 60,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 155,
    name: 'FETUCCINI*300GR',
    price: 12,
    itemId: 26,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 480,
    name: 'GORRO DESCARTABLE',
    price: 12,
    itemId: 61,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 306,
    name: 'GRAPAS X CAJA',
    price: 12,
    itemId: 104,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 308,
    name: 'GUANTE DE PLASTICO',
    price: 12,
    itemId: 62,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 464,
    name: 'GUANTES DESCARTABLE',
    price: 12,
    itemId: 64,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 190,
    name: 'HARINA DE MAIZ KILOS',
    price: 12,
    itemId: 2,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 451,
    name: 'HOTDOG KILOS',
    price: 12,
    itemId: 10,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 621,
    name: 'JABON LIQUIDO GALON',
    price: 12,
    itemId: 18,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 452,
    name: 'JAMON PIZZA KILOS',
    price: 12,
    itemId: 11,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 154,
    name: 'LASAGNA',
    price: 12,
    itemId: 27,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 313,
    name: 'LAVA VAJILLA',
    price: 12,
    itemId: 63,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 314,
    name: 'LEJIA GALON',
    price: 12,
    itemId: 65,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 315,
    name: 'LIGAS',
    price: 12,
    itemId: 105,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 316,
    name: 'LIMPIA VIDRIOS',
    price: 12,
    itemId: 66,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 157,
    name: 'MACARRON*300GR',
    price: 12,
    itemId: 28,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 16,
    name: 'MANTECA',
    price: 12,
    itemId: 78,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 602,
    name: 'MASA FAMILIAR *500GR',
    price: 12,
    itemId: 20,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 603,
    name: 'MASA GIGANTE *700GR',
    price: 12,
    itemId: 21,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 1564,
    name: 'MASA GRANDE *250GR',
    price: 12,
    itemId: 22,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 757,
    name: 'MASA LARGE *365GR',
    price: 12,
    itemId: 23,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 144,
    name: 'MASA MEDIANA *180GR',
    price: 12,
    itemId: 24,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 493,
    name: 'MASCARILLA DESCARTABLE',
    price: 12,
    itemId: 67,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 534,
    name: 'OREGANO SACHET BLS X 100 GR',
    price: 12,
    itemId: 57,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 201,
    name: 'PAN FRANCES',
    price: 12,
    itemId: 91,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 323,
    name: 'PAÑO ABSORBENTE',
    price: 12,
    itemId: 68,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 612,
    name: 'PAÑO ABSORVENTE VIRUTEX',
    price: 12,
    itemId: 69,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 356,
    name: 'PAPEL JUMBO',
    price: 12,
    itemId: 70,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 327,
    name: 'PAPEL TOALLA',
    price: 12,
    itemId: 71,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 591,
    name: 'PEPERONI KILOS',
    price: 12,
    itemId: 12,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 583,
    name: 'PERFUMADOR GALON',
    price: 12,
    itemId: 19,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 121,
    name: 'PIMIENTO KG',
    price: 12,
    itemId: 88,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 196,
    name: 'PIMIENTO UND',
    price: 12,
    itemId: 37,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 328,
    name: 'PINESOL GALON',
    price: 12,
    itemId: 72,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 659,
    name: 'PIÑA EN ALMIBAR LATA X1790',
    price: 12,
    itemId: 16,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 159,
    name: 'POMAROLA X 1KG',
    price: 12,
    itemId: 32,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 182,
    name: 'QUESO  LASAGNA *120 GR',
    price: 12,
    itemId: 45,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 605,
    name: 'QUESO FAMILIAR *320GR',
    price: 12,
    itemId: 42,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 1672,
    name: 'QUESO FAMILIAR EXPRESS *190GR',
    price: 12,
    itemId: 44,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 606,
    name: 'QUESO GIGANTE *410GR',
    price: 12,
    itemId: 43,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 1563,
    name: 'QUESO GRANDE *170GR',
    price: 12,
    itemId: 39,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 756,
    name: 'QUESO LARGE *240GR',
    price: 12,
    itemId: 40,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 766,
    name: 'QUESO LONJA *30GR.',
    price: 12,
    itemId: 41,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 147,
    name: 'QUESO MEDIANO *95GR',
    price: 12,
    itemId: 47,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 192,
    name: 'QUESO PARMESANO PORC X 100GR',
    price: 12,
    itemId: 49,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 181,
    name: 'QUESO PORC *60 GR',
    price: 12,
    itemId: 46,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 335,
    name: 'RECOGEDOR',
    price: 12,
    itemId: 73,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 710,
    name: 'ROLLO FILM 30X30 DARNET',
    price: 12,
    itemId: 106,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 455,
    name: 'SALAME KILOS',
    price: 12,
    itemId: 13,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 269,
    name: 'SALSA ALFREDO SALAMANCA X 100GR',
    price: 12,
    itemId: 33,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 161,
    name: 'SALSA ALFREDO X 220GR',
    price: 12,
    itemId: 34,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 202,
    name: 'SALSA BBQ X BOLSA 1KG',
    price: 12,
    itemId: 3,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 160,
    name: 'SALSA TUCO X 220GR',
    price: 12,
    itemId: 35,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 336,
    name: 'SECADOR',
    price: 12,
    itemId: 74,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 337,
    name: 'SERVILLETAS',
    price: 12,
    itemId: 75,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 156,
    name: 'SPAGUETTI*300GR',
    price: 12,
    itemId: 29,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 1501,
    name: 'TAPER DELY 1KG',
    price: 12,
    itemId: 82,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 344,
    name: 'TENEDORES',
    price: 12,
    itemId: 107,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 456,
    name: 'TOCINO KILOS',
    price: 12,
    itemId: 14,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 345,
    name: 'TRAPEADOR',
    price: 12,
    itemId: 76,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 346,
    name: 'TRAPO INDUSTRIAL',
    price: 12,
    itemId: 77,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
  {
    id: 349,
    name: 'VASOS 7 ONZAS*50UNI',
    price: 12,
    itemId: 108,
    unitMeasureCode: 'UN',
    measure: { code: 'UN', name: 'Unidad', factor: 1 },
  },
]
