const alpha =
  'a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,aa,ab,ac,ad,ae,af,ag,ah,ai,aj,ak,al,am,an,ao,ap,aq,ar,as,at,au,av,aw,ax,ay,az,ba,bb'
    .toUpperCase()
    .split(',')

export type FolderSchema = {
  header: string[]
  headerJson: Record<string, string>
}

export const izipayAmexSchema: FolderSchema = {
  header: alpha.slice(0, 23),
  headerJson: {
    A: 'codigo',
    B: 'producto',
    C: 'tipo_mov',
    D: 'fecha_proceso',
    E: 'fecha_lote',
    F: 'lote_manual',
    G: 'lote_pos',
    H: 'terminal',
    I: 'voucher',
    J: 'autorizacion',
    K: 'cuotas',
    L: 'tarjeta',
    M: 'origen',
    N: 'transaccion',
    O: 'fecha_consumo',
    P: 'importe',
    Q: 'comision',
    R: 'comision_merchant',
    S: 'igv',
    T: 'neto_parcial',
    U: 'neto_total',
    V: 'fecha_abono',
    W: 'observaciones',
  },
}

export const izipayDinnerSchema: FolderSchema = {
  header: alpha.slice(0, 24),
  headerJson: {
    A: 'codigo',
    B: 'producto',
    C: 'tipo_mov',
    D: 'fecha_proceso',
    E: 'fecha_lote',
    F: 'lote_manual',
    G: 'lote_pos',
    H: 'terminal',
    I: 'voucher',
    J: 'autorizacion',
    K: 'cuotas',
    L: 'tarjeta',
    M: 'origen',
    N: 'transaccion',
    O: 'fecha_consumo',
    P: 'importe',
    Q: 'status',
    R: 'comision',
    S: 'igv',
    T: 'neto_parcial',
    U: 'neto_total',
    V: 'fecha_abono',
    W: 'fecha_abono_8dig',
    X: 'observaciones',
  },
}

export const izipayMcSchema: FolderSchema = {
  header: alpha.slice(0, 25),
  headerJson: {
    A: 'codigo',
    B: 'producto',
    C: 'tipo_mov',
    D: 'fecha_proceso',
    E: 'fecha_lote',
    F: 'lote_manual',
    G: 'lote_pos',
    H: 'terminal',
    I: 'voucher',
    J: 'autorizacion',
    K: 'cuotas',
    L: 'tarjeta',
    M: 'origen',
    N: 'transaccion',
    O: 'fecha_consumo',
    P: 'importe',
    Q: 'status',
    R: 'comision',
    S: 'comision_afecta',
    T: 'igv',
    U: 'neto_parcial',
    V: 'neto_total',
    W: 'fecha_abono',
    X: 'fecha_abono_8dig',
    Y: 'observaciones',
  },
}

export const izipayPosSchema: FolderSchema = {
  header: alpha.slice(0, 25),
  headerJson: {
    A: 'codigo',
    B: 'tipo de movimiento',
    C: 'tipo de captura',
    D: 'transaccion',
    E: 'fecha de transaccion',
    F: 'hora de transaccion',
    G: 'fecha de cierre de lote',
    H: 'fecha de proceso',
    I: 'fecha de abono',
    J: 'estado',
    K: 'importe',
    L: 'comision',
    M: 'igv',
    N: 'importe neto',
    O: 'abono del lote',
    P: 'num de lote',
    Q: 'terminal',
    R: 'num de ref (voucher)',
    S: 'marca de tarjeta',
    T: 'num de tarjeta',
    U: 'codigo de autorizacion',
    V: 'cuotas',
    W: 'observaciones',
    X: 'moneda',
    Y: 'serie terminal',
  },
}

export const culqiAbonoSchema: FolderSchema = {
  header: alpha.slice(0, 15),
  headerJson: {
    A: 'concepto',
    B: 'fecha abono',
    C: 'hora abono',
    D: 'fecha venta',
    E: 'hora venta',
    F: 'id abono',
    G: 'id voucher',
    H: 'código autorización',
    I: 'id venta',
    J: 'moneda',
    K: 'monto',
    L: 'com. variable',
    M: 'com. fija',
    N: 'igv',
    O: 'abonado',
  },
}

export const culqiOnlineSchemaAntes: FolderSchema = {
  header: alpha.slice(0, 43),
  headerJson: {
    A: 'id venta',
    B: 'id cliente',
    C: 'id cargo',
    D: 'nombres cliente',
    E: 'apellidos cliente',
    F: 'correo electronico cliente',
    G: 'marca',
    H: 'ult. 4 digitos',
    I: 'moneda',
    J: 'fecha de la transaccion',
    K: 'hora de la transaccion',
    L: 'codigo respuesta',
    M: 'descripcion producto',
    N: 'nombres (tarjeta)',
    O: 'apellidos (tarjeta)',
    P: 'correo electronico (tarjeta)',
    Q: 'pais',
    R: 'ciudad',
    S: 'direccion',
    T: 'telefono',
    U: 'nombre banco',
    V: 'pais banco',
    W: 'producto',
    X: 'codigo referencia',
    Y: 'ticket',
    Z: 'codigo autorizacion',
    AA: 'fecha devolución',
    AB: 'devolucion',
    AC: 'monto venta',
    AD: 'venta final total',
    AE: 'comision variable total',
    AF: 'comision fija total',
    AG: 'igv total',
    AH: 'comision total',
    AI: 'monto aproximado abono total',
    AJ: 'metadata',
    AK: 'estado',
    AL: 'mensaje al comercio',
    AM: 'mensaje al usuario',
    AN: 'tipo pago',
    AO: 'nro pedido',
    AP: 'fecha de expiracion',
    AQ: 'cuota sin interés',
  },
}
export const culqiPosSchemaAntes: FolderSchema = {
  header: alpha.slice(0, 49),
  headerJson: {
    A: 'id venta',
    B: 'id cliente',
    C: 'id cargo',
    D: 'nombres cliente',
    E: 'apellidos cliente',
    F: 'correo electronico cliente',
    G: 'marca',
    H: 'ult. 4 digitos',
    I: 'moneda',
    J: 'fecha de la transaccion',
    K: 'hora de la transaccion',
    L: 'codigo respuesta',
    M: 'descripcion producto',
    N: 'nombres (tarjeta)',
    O: 'apellidos (tarjeta)',
    P: 'correo electronico (tarjeta)',
    Q: 'pais',
    R: 'ciudad',
    S: 'direccion',
    T: 'nombre banco',
    U: 'pais banco',
    V: 'producto',
    W: 'codigo referencia',
    X: 'ticket',
    Y: 'codigo autorizacion',
    Z: 'terminal',
    AA: 'fecha devolución',
    AB: 'devolucion',
    AC: 'monto venta',
    AD: 'comisión variable venta',
    AE: 'igv venta',
    AF: 'comisión venta',
    AG: 'monto aproximado abono venta',
    AH: 'monto propina',
    AI: 'comisión variable propina',
    AJ: 'igv propina',
    AK: 'comisión propina',
    AL: 'monto aproximado abono propina',
    AM: 'venta final total',
    AN: 'comision variable total',
    AO: 'igv total',
    AP: 'comision total',
    AQ: 'monto aproximado abono total',
    AR: 'id voucher',
    AS: 'serie terminal',
    AT: 'estado',
    AU: 'mensaje al comercio',
    AV: 'mensaje al usuario',
    AW: 'tipo pago',
  },
}

export const culqiOnlineSchema: FolderSchema = {
  header: alpha.slice(0, 45),
  headerJson: {
    A: 'ID Venta',
    B: 'ID Cliente',
    C: 'ID Cargo',
    D: 'Nombres Cliente',
    E: 'Apellidos Cliente',
    F: 'Correo Electronico Cliente',
    G: 'Marca',
    H: 'Ult. 4 digitos',
    I: 'Moneda',
    J: 'Fecha de la transaccion',
    K: 'Hora de la transaccion',
    L: 'Codigo Respuesta',
    M: 'Descripcion Producto',
    N: 'Nombres (Tarjeta)',
    O: 'Apellidos (Tarjeta)',
    P: 'Correo Electronico (Tarjeta)',
    Q: 'Pais',
    R: 'Ciudad',
    S: 'Direccion',
    T: 'Telefono',
    U: 'Nombre Banco',
    V: 'Pais Banco',
    W: 'Producto',
    X: 'Codigo Referencia',
    Y: 'Ticket',
    Z: 'Codigo Autorizacion',
    AA: 'Fecha Devolución',
    AB: 'Devolucion',
    AC: 'Monto VENTA',
    AD: 'Venta Final TOTAL',
    AE: 'Comision variable TOTAL',
    AF: 'Comision fija TOTAL',
    AG: 'IGV TOTAL',
    AH: 'Comision TOTAL',
    AI: 'Monto Aproximado Abono TOTAL',
    AJ: 'Metadata',
    AK: 'Fecha aproximada abono',
    AL: 'Estado',
    AM: 'Mensaje al Comercio',
    AN: 'Mensaje al Usuario',
    AO: 'Tipo pago',
    AP: 'Nro Pedido',
    AQ: 'Fecha de expiracion',
    AR: 'Cuota sin interés',
    AS: 'Nro. Cuotas',
  },
}

export const culqiPosSchemaVeryOld: FolderSchema = {
  header: alpha.slice(0, 53),
  headerJson: {
    A: 'ID Venta',
    B: 'ID Cliente',
    C: 'ID Cargo',
    D: 'Nombres Cliente',
    E: 'Apellidos Cliente',
    F: 'Correo Electronico Cliente',
    G: 'Marca',
    H: 'Nro. Tarjeta',
    I: 'Ult. 4 digitos',
    J: 'Moneda',
    K: 'Fecha de la transaccion',
    L: 'Hora de la transaccion',
    M: 'Codigo Respuesta',
    N: 'Descripcion Producto',
    O: 'Nombres (Tarjeta)',
    P: 'Apellidos (Tarjeta)',
    Q: 'Correo Electronico (Tarjeta)',
    R: 'Pais',
    S: 'Ciudad',
    T: 'Direccion',
    U: 'Nombre Banco',
    V: 'Pais Banco',
    W: 'Producto',
    X: 'Codigo Referencia',
    Y: 'Ticket',
    Z: 'Codigo Autorizacion',
    AA: 'terminal',
    AB: 'Devolucion',
    AC: 'Monto VENTA',
    AD: 'Comisión Variable VENTA',
    AE: 'IGV VENTA',
    AF: 'Comisión VENTA',
    AG: 'Monto Aproximado Abono VENTA',
    AH: 'Monto PROPINA',
    AI: 'Comisión Variable PROPINA',
    AJ: 'IGV PROPINA',
    AK: 'Comisión PROPINA',
    AL: 'Monto Aproximado Abono PROPINA',
    AM: 'Venta Final TOTAL',
    AN: 'Comision variable TOTAL',
    AO: 'IGV TOTAL',
    AP: 'Comision TOTAL',
    AQ: 'Monto Aproximado Abono TOTAL',
    AR: 'ID Voucher',
    AS: 'Serie Terminal',
    AT: 'Fecha aproximada abono',
    AU: 'Estado',
    AV: 'Mensaje al Comercio',
    AW: 'Mensaje al Usuario',
    AX: 'Tipo pago',
    AY: 'Marca QR',
    AZ: 'ID QR',
    BA: 'Numero de celular',
  },
}

export const culqiPosSchemaOld: FolderSchema = {
  header: alpha.slice(0, 46),
  headerJson: {
    A: 'ID Venta',
    B: 'ID Cliente',
    C: 'ID Cargo',
    D: 'Nombres Cliente',
    E: 'Apellidos Cliente',
    F: 'Correo Electronico Cliente',
    G: 'Marca',
    H: 'Ult. 4 digitos',
    I: 'Moneda',
    J: 'Fecha de la transaccion',
    K: 'Hora de la transaccion',
    L: 'Codigo Respuesta',
    M: 'Descripcion Producto',
    N: 'Nombres (Tarjeta)',
    O: 'Apellidos (Tarjeta)',
    P: 'Correo Electronico (Tarjeta)',
    Q: 'Pais',
    R: 'Ciudad',
    S: 'Direccion',
    T: 'Telefono',
    U: 'Nombre Banco',
    V: 'Pais Banco',
    W: 'Producto',
    X: 'Codigo Referencia',
    Y: 'Ticket',
    Z: 'Codigo Autorizacion',
    AA: 'Fecha Devolución',
    AB: 'Devolucion',
    AC: 'Monto VENTA',
    AD: 'Venta Final TOTAL',
    AE: 'Comision variable TOTAL',
    AF: 'Comision fija TOTAL',
    AG: 'IGV TOTAL',
    AH: 'Comision TOTAL',
    AI: 'Monto Aproximado Abono TOTAL',
    AJ: 'Metadata',
    AK: 'Fecha aproximada abono',
    AL: 'Estado',
    AM: 'Mensaje al Comercio',
    AN: 'Mensaje al Usuario',
    AO: 'Tipo pago',
    AP: 'Nro Pedido',
    AQ: 'Fecha de expiracion',
    AR: 'Cuota sin interés',
    AS: 'Nro. Cuotas',
    AT: 'Comision CSI',
  },
}

export const culqiPosSchema: FolderSchema = {
  header: alpha.slice(0, 53),
  headerJson: {
    A: 'ID Venta',
    B: 'ID Cliente',
    C: 'ID Cargo',
    D: 'Nombres Cliente',
    E: 'Apellidos Cliente',
    F: 'Correo Electronico Cliente',
    G: 'Marca',
    H: 'Nro. Tarjeta',
    I: 'Ult. 4 digitos',
    J: 'Moneda',
    K: 'Fecha de la transaccion',
    L: 'Hora de la transaccion',
    M: 'Codigo Respuesta',
    N: 'Descripcion Producto',
    O: 'Nombres (Tarjeta)',
    P: 'Apellidos (Tarjeta)',
    Q: 'Correo Electronico (Tarjeta)',
    R: 'Pais',
    S: 'Ciudad',
    T: 'Direccion',
    U: 'Nombre Banco',
    V: 'Pais Banco',
    W: 'Producto',
    X: 'Codigo Referencia',
    Y: 'Ticket',
    Z: 'Codigo Autorizacion',
    AA: 'terminal',
    AB: 'Devolucion',
    AC: 'Monto VENTA',
    AD: 'Comisión Variable VENTA',
    AE: 'IGV VENTA',
    AF: 'Comisión VENTA',
    AG: 'Monto Aproximado Abono VENTA',
    AH: 'Monto PROPINA',
    AI: 'Comisión Variable PROPINA',
    AJ: 'IGV PROPINA',
    AK: 'Comisión PROPINA',
    AL: 'Monto Aproximado Abono PROPINA',
    AM: 'Venta Final TOTAL',
    AN: 'Comision variable TOTAL',
    AO: 'IGV TOTAL',
    AP: 'Comision TOTAL',
    AQ: 'Monto Aproximado Abono TOTAL',
    AR: 'ID Voucher',
    AS: 'Serie Terminal',
    AT: 'Fecha aproximada abono',
    AU: 'Estado',
    AV: 'Mensaje al Comercio',
    AW: 'Mensaje al Usuario',
    AX: 'Tipo pago',
    AY: 'Marca QR',
    AZ: 'ID QR',
    BA: 'Numero de celular',
  },
}
