/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Decimal = ColumnType<string, number | string>;

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = ColumnType<JsonValue, string, string>;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface AdmCompany {
  company_ruc: string | null;
  created_at: Generated<Date>;
  has_accounting: Generated<number>;
  id: string;
  status: Generated<number>;
  title: string;
  /**
   * C: Comercial 
   */
  type_company: Generated<string>;
  updated_at: Generated<Date>;
}

export interface AdmPaymentOrder {
  amount: Generated<Decimal | null>;
  approved1_by: string;
  approved2_by: string;
  bankaccount_name: string | null;
  bankaccount_number: string | null;
  bankaccount_type: string | null;
  cashbank_id: number;
  company_id: string;
  created_at: Generated<Date>;
  id: Generated<number>;
  money: Generated<string | null>;
  operation: string;
  payment_at: Date | null;
  required_at: Date | null;
  required_by: string;
  /**
   * I: Ingresado; A: Autorizado; N: Enviado Banco;  R: Rechazado; P: Pagado X: Anulado 
   */
  status: string;
  updated_at: Generated<Date>;
}

export interface AdmReqContract {
  amount: Decimal | null;
  company_id: string;
  contract_code: string;
  contract_type: string;
  created_at: Generated<Date>;
  description: string | null;
  effective_at: Date | null;
  expires_at: Date | null;
  id: Generated<number>;
  legal_name: string | null;
  legal_number: string | null;
  money: Generated<string | null>;
  pay_frequency: string | null;
  /**
   * CONTADO / CREDITO
   */
  pay_method: string | null;
  quotas: Generated<number | null>;
  /**
   * I: Ingresado;V:Vigente; E: Expirado; P: Pagado; X: Anulado
   */
  status: string;
  status_name: string;
  supplier_code: string | null;
  supplier_id: number;
  updated_at: Generated<Date>;
  /**
   * vigencia
   */
  validity: string | null;
}

export interface AdmReqFile {
  created_at: Generated<Date>;
  created_by: string | null;
  doc_date: Date | null;
  doc_description: string | null;
  doc_move_id: number | null;
  doc_number: string | null;
  doc_ocr: string | null;
  doc_request_id: number | null;
  doc_type: string | null;
  doc_url: string | null;
  id: Generated<number>;
}

export interface AdmReqLog {
  created_at: Generated<Date>;
  id: Generated<number>;
  person_mail: string;
  person_name: string;
  request_id: number;
  /**
   * S: Solicitado; A: Aprobado;  P: Pagado; R: Rechazado;  B: contaBilizado
   */
  status_id: string;
  status_name: string;
  updated_at: Generated<Date>;
}

export interface AdmReqNondocs {
  amount: Decimal | null;
  autoentry_id: number | null;
  cashbank_source_id: number | null;
  cashbank_target_id: number | null;
  company_id: string | null;
  created_at: Generated<Date>;
  created_by: string | null;
  description: string | null;
  doc_url: string | null;
  id: Generated<number>;
  money: Generated<string | null>;
  movetype_id: number | null;
  payment_order_id: number | null;
  /**
   * REQ1234567
   */
  request_code: string | null;
  /**
   * U: Proveedor; S: Simple; T: Transferencia; L: Liquidacion
   */
  request_type: string | null;
  requested_at: Date | null;
  /**
   * I: Ingresado; D: Programado; A: Aprobado; N: Enviado Banco;  R: Rechazado; P: Pagado X: Anulado (S: Solicitado; A: Aprobado;  P: Pagado; R: Rechazado;)
   */
  status: Generated<string>;
  updated_at: Generated<Date>;
}

export interface AdmRequirement {
  amount: Decimal | null;
  amount_net: Decimal | null;
  amount_ret: Decimal | null;
  autoentry_id: number | null;
  cashbank_id: number | null;
  company_id: string | null;
  contract_id: number | null;
  costcenter_id: number | null;
  created_at: Generated<Date>;
  created_by: string | null;
  description: string | null;
  doc_url: string | null;
  expires_at: Date | null;
  /**
   * 1: No tiene; 1: Si tiene
   */
  has_retention: Generated<string | null>;
  id: Generated<number>;
  legal_name: string | null;
  legal_number: string | null;
  money: Generated<string | null>;
  movetype_id: number | null;
  num_contract: string | null;
  num_document: string | null;
  /**
   * CONTADO / CREDITO
   */
  pay_method: string | null;
  payment_order_id: number | null;
  purchase_id: number | null;
  /**
   * REQ1234567
   */
  request_code: string | null;
  /**
   * U: Proveedor; S: Simple; T: Transferencia; L: Liquidacion
   */
  request_type: string | null;
  requested_at: Date | null;
  /**
   * I: Ingresado; D: Programado; A: Aprobado; N: Enviado Banco;  R: Rechazado; P: Pagado X: Anulado (S: Solicitado; A: Aprobado;  P: Pagado; R: Rechazado;)
   */
  status: Generated<string>;
  supplier_id: number | null;
  /**
   * 01 Factura; 03 Boleta; 04 Ticket de Salida; 07 Nota de crédito; 08 Nota de débito; 09 Guia remisión; 31 Guia transportista
   */
  type_document: string | null;
  updated_at: Generated<Date>;
}

export interface AdmSucursal {
  cfd_igv: Decimal | null;
  cfd_seql_bo: number | null;
  cfd_seql_fa: number | null;
  cfd_seql_gr: number | null;
  cfd_serie_bo: string | null;
  cfd_serie_fa: string | null;
  cfd_serie_gr: string | null;
  company_id: string | null;
  created_at: Generated<Date>;
  efact_pass: string | null;
  guide_template: string | null;
  id: string;
  legalperson_account_bco: string | null;
  legalperson_account_cci: string | null;
  legalperson_account_cur: string | null;
  legalperson_account_num: string | null;
  legalperson_account_type: string | null;
  legalperson_docnum: string | null;
  legalperson_doctype: string | null;
  legalperson_name: string | null;
  sede_nro_ruc: string | null;
  sede_razon_social: string | null;
  status: Generated<number>;
  title: string;
  /**
   * T: Tienda, A: Almacen, O: Oficina
   */
  type_sede: string | null;
  ubi_address: string | null;
  ubi_city: string | null;
  ubi_district: string | null;
  ubi_route: string | null;
  updated_at: Generated<Date>;
}

export interface AdmSucursalMove {
  amount: Decimal | null;
  approved_at: Date | null;
  approved_by: string | null;
  cashbank_account: string | null;
  cashbank_id: number | null;
  company_id: string | null;
  created_at: Generated<Date>;
  created_by: string | null;
  description: string | null;
  expires_at: Date | null;
  id: Generated<number>;
  movetype_account: string | null;
  movetype_id: number | null;
  rejected_at: Date | null;
  rejected_by: string | null;
  requested_at: Date | null;
  /**
   * P: Pendiente;  F: Firmado; A: Aprobado; E:???; C: Cerrado;  B: contaBilizado
   */
  status: Generated<string>;
  updated_at: Generated<Date>;
}

export interface AdmTerminalpos {
  created_at: Generated<Date>;
  id: Generated<number>;
  status: Generated<number>;
  sucursal_id: string | null;
  supplier: string | null;
  terminal: string;
  updated_at: Generated<Date>;
}

export interface BnkReconciliation {
  bnk_agencia: string | null;
  bnk_fecha: Date | null;
  bnk_monto: Decimal | null;
  bnk_name: string | null;
  bnk_operacion_num: string | null;
  bnk_operacion_text: string | null;
  bnk_referencia: string | null;
  bnk_saldo: Decimal | null;
  bnk_usuario: string | null;
  bnk_utc: string | null;
  created_at: Generated<Date>;
  req_description: string | null;
  req_id: number | null;
  req_monto: Decimal | null;
  transactionkey: string;
  updated_at: Generated<Date>;
  updated_by: string | null;
}

export interface ExtPagosCulqi {
  apellidoscliente: string | null;
  apellidostarjeta: string | null;
  aplicacion: string | null;
  cashmove_id: string | null;
  ciudad: string | null;
  codigoautorizacion: string | null;
  codigoreferencia: string | null;
  codigorespuesta: string | null;
  comisionfijatotal: Decimal | null;
  comisionpropina: Decimal | null;
  comisiontotal: Decimal | null;
  comisionvariablepropina: Decimal | null;
  comisionvariabletotal: Decimal | null;
  comisionvariableventa: Decimal | null;
  comisionventa: Decimal | null;
  copiedto_dw: Generated<number>;
  correoelectronicocliente: string | null;
  correoelectronicotarjeta: string | null;
  created_at: Generated<Date>;
  descripcionproducto: string | null;
  devolucion: number | null;
  direccion: string | null;
  estado: string | null;
  fechadeabono: Date | null;
  fechadeabono_iso: string | null;
  fechadelatransaccion: Date | null;
  fechadelatransaccion_iso: string | null;
  fechadevolucion: Date | null;
  idcargo: string | null;
  idcliente: string | null;
  idventa: string | null;
  idvoucher: string | null;
  igvpropina: Decimal | null;
  igvtotal: Decimal | null;
  igvventa: Decimal | null;
  marca: string | null;
  moneda: string | null;
  montoabonofinal: Decimal | null;
  montoaproximadoabonopropina: Decimal | null;
  montoaproximadoabonototal: Decimal | null;
  montoaproximadoabonoventa: Decimal | null;
  montopropina: Decimal | null;
  montoventa: Decimal | null;
  nombrebanco: string | null;
  nombrescliente: string | null;
  nombrestarjeta: string | null;
  nropedido: string | null;
  nrotarjeta: string | null;
  pais: string | null;
  paisbanco: string | null;
  producto: string | null;
  requestpay_id: string | null;
  serieterminal: string | null;
  sucursalcode: string | null;
  sucursalnombre: string | null;
  telefono: string | null;
  terminal: string | null;
  ticket: string | null;
  tipopago: string | null;
  transactionkey: string;
  ult4digitos: string | null;
  ventafinaltotal: Decimal | null;
}

export interface ExtPagosIzipay {
  abonodelote: Decimal | null;
  cashmove_id: string | null;
  codigo: string | null;
  codigodeautorizacion: string | null;
  comision: Decimal | null;
  copiedto_dw: Generated<number>;
  created_at: Generated<Date>;
  cuotas: number | null;
  estado: string | null;
  fechadeabono: Date | null;
  fechadeabono_iso: string | null;
  fechadecierredelote: Date | null;
  fechadeproceso: Date | null;
  fechadetransaccion: Date | null;
  fechadetransaccion_iso: string | null;
  igv: Decimal | null;
  importe: Decimal | null;
  importeneto: Decimal | null;
  marcadetarjeta: string | null;
  moneda: string | null;
  numdelote: number | null;
  numderef: number | null;
  numdetarjeta: string | null;
  observaciones: string | null;
  requestpay_id: string | null;
  serieterminal: string | null;
  sucursalcode: string | null;
  sucursalnombre: string | null;
  terminal: string | null;
  tipodecaptura: string | null;
  tipodemovimiento: string | null;
  transaccion: string | null;
  transactionkey: string;
}

export interface FinAccount {
  account: string;
  account_father: string;
  company_id: string | null;
  created_at: Generated<Date>;
  created_by: Generated<string>;
  /**
   * cuenta contable
   */
  id: string;
  is_father: Generated<number>;
  level: Generated<number>;
  status: Generated<number>;
  type_account: string;
  updated_at: Generated<Date>;
  visible: Generated<number>;
}

export interface FinAutoentry {
  created_at: Generated<Date>;
  created_by: Generated<string>;
  id: Generated<number>;
  /**
   * 0: simple, 1: simple multiple, 2: multiple full
   */
  is_multiple: Generated<number>;
  status: Generated<number>;
  title: string;
  /**
   * P: Programado; M: Manual
   */
  type_entry: Generated<string>;
  updated_at: Generated<Date>;
}

export interface FinAutoentryItem {
  account_id: string;
  company_id: string;
  created_at: Generated<Date>;
  entry_id: number;
  entry_number: Generated<number>;
  flow: string;
  id: Generated<number>;
  is_multiple: Generated<string>;
  updated_at: Generated<Date>;
}

export interface FinBalance {
  account_id: string;
  balance_at: Date;
  balance_code: string | null;
  balance_credit: Generated<Decimal>;
  balance_debit: Generated<Decimal>;
  balance_last: Generated<Decimal>;
  balance_total: Generated<Decimal>;
  company_id: string;
  created_at: Generated<Date>;
  created_by: Generated<string>;
  eerr_period: string | null;
  id: Generated<number>;
  updated_at: Generated<Date>;
}

export interface FinCashbank {
  account_id: string | null;
  cashbank: string;
  company_id: string | null;
  created_at: Generated<Date>;
  id: Generated<number>;
  status: Generated<number>;
  sucursal_id: string | null;
  /**
   * 1: Tiendas; 3: Banco; 4: Central; 5: Corales; 6: Liquidadora
   */
  type_cash: number;
  updated_at: Generated<Date>;
}

export interface FinCashbankBalance {
  account_id: number;
  balance: Decimal | null;
  balance_at: Date | null;
  cashbank_id: number;
  created_at: Generated<Date>;
  created_by: string | null;
  id: Generated<number>;
  status_request: string | null;
}

export interface FinCostcenter {
  account_link1: string | null;
  account_link2: string | null;
  account_link3: string | null;
  company_id: string | null;
  costcenter: string;
  created_at: Generated<Date>;
  id: Generated<number>;
  status: Generated<number>;
  sucursal_id: string | null;
  /**
   * T: Tienda / A: Area oficina
   */
  type_cc: Generated<string | null>;
  updated_at: Generated<Date>;
}

export interface FinJournalentry {
  company_id: string;
  company_name: string;
  contributor_name: string | null;
  contributor_ruc: string | null;
  cost_center_id: number;
  created_at: Generated<Date>;
  created_by: Generated<string>;
  /**
   * F: Factura / B: Boleta
   */
  doc_type: string | null;
  gloss: string;
  id: Generated<number>;
  move_at: Date;
  move_id: number;
  /**
   * C (Compra) 
   */
  move_type: string | null;
  num_doc: string | null;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface FinJournalentryItem {
  account_id: string;
  account_name: string | null;
  /**
   * Credito es Abono
   */
  amount_credit: Decimal | null;
  /**
   * Debito es Cargo
   */
  amount_debit: Decimal | null;
  cash_account_move_id: number | null;
  cash_lote_id: string | null;
  created_at: Generated<Date>;
  eerr_period: string | null;
  id: Generated<number>;
  journalentry_id: number;
  updated_at: Generated<Date>;
}

export interface FinMoneyChange {
  created_at: Generated<Date>;
  exchange_rate: Generated<Decimal | null>;
  id: Generated<number>;
  money_base: string;
  /**
   * 1: Tiendas; 3: Banco; 4: Central; 5: Corales; 6: Liquidadora
   */
  money_target: string;
  rate_at: Date | null;
  updated_at: Generated<Date>;
}

export interface FinMovetype {
  /**
   * S: Salida; I: Ingreso
   */
  account_flow: Generated<string>;
  account_id: string | null;
  /**
   * S: Salida; I: Ingreso
   */
  cash_flow: Generated<string>;
  created_at: Generated<Date>;
  id: Generated<number>;
  movetype: string;
  /**
   * G: Gasto; V: Venta
   */
  origin_from: Generated<string>;
  status: Generated<number>;
  updated_at: Generated<Date>;
  /**
   * 1: Para las tiendas; 4: Para requerimientos; 7: Para multiple
   */
  used_to: Generated<number>;
}

export interface IamFunction {
  created_at: Generated<Date>;
  function: string;
  id: Generated<number>;
  module_id: number | null;
  path_function: string | null;
  path_view: string | null;
  priority: number | null;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface IamLog {
  action: string | null;
  created_at: Generated<Date>;
  id: Generated<number>;
  module_id: number | null;
  script: string | null;
  user_id: number | null;
}

export interface IamModule {
  created_at: Generated<Date>;
  id: Generated<number>;
  module: string;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface IamPermission {
  function_id: number | null;
  granted: number | null;
  id: Generated<number>;
  module_id: number | null;
  role_id: number | null;
}

export interface IamRole {
  created_at: Generated<Date>;
  id: Generated<number>;
  role: string;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface IamUser {
  created_at: Generated<Date>;
  email: string;
  email_token: string | null;
  email_validate: Generated<string>;
  id: Generated<number>;
  name: string;
  password: string;
  phone: string | null;
  role_id: number | null;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface InvBrand {
  brand: string;
  code: string | null;
  created_at: Generated<Date>;
  id: Generated<number>;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface InvCarrier {
  carrier_name: string;
  /**
   * transportista nro de doc 
   */
  carrier_nro_doc: string | null;
  /**
   * razon social transportista
   */
  carrier_razon_social: string | null;
  /**
   * transportista tipo de doc
   */
  carrier_tipo_doc: Generated<string | null>;
  /**
   * conductor apellidos
   */
  conductor_apellidos: string | null;
  /**
   * conductor nombres
   */
  conductor_nombres: string | null;
  /**
   * nro de doc conductor
   */
  conductor_nro_doc: string | null;
  /**
   * nro de licencia de conductor
   */
  conductor_nro_licencia: string | null;
  /**
   * tipo de conductor
   */
  conductor_tipo: string | null;
  /**
   * tipo de doc de conductor
   */
  conductor_tipo_doc: string | null;
  created_at: Generated<Date>;
  id: Generated<number>;
  /**
   * 1: Nuevo; 2: Pendiente y recibido; 3: En revisión; 4: En observación; 5: Alta; 9: Baja
   */
  status: Generated<number>;
  /**
   * nro de placa de vehiculo principal
   */
  transporte_nro_placa: string | null;
  updated_at: Generated<Date>;
}

export interface InvCategory {
  category: string;
  created_at: Generated<Date>;
  id: Generated<number>;
  priority: Generated<number>;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface InvDispatch {
  approved_by: string | null;
  company_id: string | null;
  /**
   * conductor apellidos
   */
  conductor_apellidos: string | null;
  /**
   * conductor nombres
   */
  conductor_nombres: string | null;
  /**
   * nro de doc conductor
   */
  conductor_nro_doc: string | null;
  /**
   * nro de licencia de conductor
   */
  conductor_nro_licencia: string | null;
  /**
   * tipo de conductor
   */
  conductor_tipo: string | null;
  /**
   * tipo de doc de conductor
   */
  conductor_tipo_doc: string | null;
  created_at: Generated<Date>;
  created_by: Generated<string>;
  doc_url: string | null;
  gloss: string | null;
  id: Generated<number>;
  move_at: Date;
  /**
   * D: Despacho almacen -tienda / M: Movimiento entre tiendas / E: Despacho excepcional
   */
  move_type: Generated<string>;
  net_value: Generated<Decimal>;
  num_guide: string | null;
  num_invoice: string | null;
  requested_by: string | null;
  /**
   * 1: Nuevo pedido por la tienda; 2: Aprobado por almacen; 3: Recibido por la tienda; 0: Anulado
   */
  status: Generated<number>;
  sucursal_from_id: string;
  sucursal_to_id: string | null;
  tax_value: Generated<Decimal>;
  total_value: Generated<Decimal>;
  /**
   * transportista nro de doc 
   */
  transporte_nro_doc: string | null;
  /**
   * nro de placa de vehiculo principal
   */
  transporte_nro_placa: string | null;
  /**
   * razon social transportista
   */
  transporte_razon_social: string | null;
  /**
   * transportista tipo de doc
   */
  transporte_tipo_doc: Generated<string | null>;
  updated_at: Generated<Date>;
}

export interface InvDispatchItem {
  created_at: Generated<Date>;
  dispatch_id: number;
  id: Generated<number>;
  item_id: number;
  item_name: string;
  measure_id: number | null;
  /**
   * peso bruto
   */
  peso_bruto: Generated<Decimal | null>;
  quantity: Generated<Decimal>;
  total_value: Generated<Decimal>;
  /**
   * modalidad traslado: 01(si es publico) o 02 (privado)
   */
  transport_mode: string | null;
  unit_value: Generated<Decimal>;
  updated_at: Generated<Date>;
  weight: Generated<Decimal>;
}

export interface InvEquivalence {
  created_at: Generated<Date>;
  id: Generated<number>;
  measure_id: number;
  presentation_from: number;
  presentation_to: number | null;
  status: Generated<number>;
  updated_at: Generated<Date>;
  value_factor: Generated<Decimal>;
  value_from: Generated<Decimal>;
}

export interface InvFormula {
  created_at: Generated<Date>;
  formula: string;
  id: Generated<number>;
  measure_id: number | null;
  performance: number;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface InvFormulaProduct {
  created_at: Generated<Date>;
  formula_id: number;
  id: Generated<number>;
  item_id: number;
  item_name: string;
  measure_id: number | null;
  presentation_id: number;
  presentation_name: string;
  quantity: Generated<Decimal>;
  updated_at: Generated<Date>;
}

export interface InvItem {
  brand_id: number;
  category_id: number | null;
  created_at: Generated<Date>;
  id: Generated<number>;
  item_code: Generated<string>;
  item_name: string;
  /**
   * O: Item de origen / D: Item derivado
   */
  item_type: Generated<string>;
  /**
   * D: Item venta directa, T: Ingrediente
   */
  item_used_to: string | null;
  measure_id: number | null;
  presentation_id: number;
  product_id: number | null;
  /**
   * 1: Nuevo; 2: Pendiente y recibido; 3: En revisión; 4: En observación; 5: Alta; 9: Baja
   */
  status: Generated<number>;
  subcategory_id: number | null;
  supplier_id: number;
  unit_cost: Generated<Decimal>;
  unit_price: Generated<Decimal>;
  updated_at: Generated<Date>;
}

export interface InvKardex {
  company_id: string | null;
  created_at: Generated<Date>;
  created_by: Generated<string>;
  id: Generated<number>;
  item_id: number;
  item_name: string;
  move_at: Date;
  /**
   * E entrada S salida
   */
  move_flow: string;
  move_id: number;
  /**
   * C compra / P produccion / D despacho / I Carga_ini
   */
  move_type: string;
  num_doc: string | null;
  quantity: Generated<Decimal>;
  /**
   * stock actual
   */
  stock_current: Generated<Decimal>;
  /**
   * ultimo stock
   */
  stock_last: Generated<Decimal>;
  total_current: Generated<Decimal>;
  total_last: Generated<Decimal>;
  /**
   * total precio venta
   */
  total_price: Generated<Decimal>;
  /**
   * 01 Factura; 03 Boleta; 04 Ticket de Salida; 07 Nota de crédito; 08 Nota de débito; 09 Guia remisión; 31 Guia transportista
   */
  type_doc: string | null;
  /**
   * precio venta
   */
  unit_price: Generated<Decimal>;
  /**
   * precio compra
   */
  unit_purchase: Generated<Decimal>;
  updated_at: Generated<Date>;
  warehouse_id: string | null;
}

export interface InvMeasure {
  code: string | null;
  created_at: Generated<Date>;
  id: Generated<number>;
  measure: string;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface InvPresentation {
  created_at: Generated<Date>;
  id: Generated<number>;
  presentation: string;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface InvProduct {
  category_id: number | null;
  created_at: Generated<Date>;
  external_code: string | null;
  formula_id: number | null;
  id: Generated<number>;
  measure_id: number | null;
  product: string;
  /**
   * 1: Nuevo; 2: Pendiente y recibido; 3: En revisión; 4: En observación; 5: Disponible; 9: Caducado
   */
  status: Generated<number>;
  unit_price: Decimal | null;
  updated_at: Generated<Date>;
}

export interface InvProductFlavor {
  company_id: string;
  created_at: Generated<Date>;
  flavor: string;
  id: Generated<number>;
  menuflav_id: number;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface InvProduction {
  created_at: Generated<Date>;
  created_by: Generated<string>;
  discount: Generated<Decimal>;
  formula_id: number;
  formula_name: string;
  id: Generated<number>;
  measure_id: number | null;
  net_value: Generated<Decimal>;
  production_at: Date;
  quantity: Generated<Decimal>;
  /**
   * 1: Nuevo; 2: Pendiente; 3: En proceso (comprando a tiendas); 4: En distribución; 5: Finalizado; 9: Extornado
   */
  status: Generated<number>;
  tax_value: Generated<Decimal>;
  total_value: Generated<Decimal>;
  unit_value: Generated<Decimal>;
  updated_at: Generated<Date>;
}

export interface InvProductionItem {
  created_at: Generated<Date>;
  id: Generated<number>;
  item_id: number;
  item_name: string;
  measure_id: number | null;
  presentation_id: number;
  presentation_name: string;
  production_id: number;
  quantity: Generated<Decimal>;
  total_value: Generated<Decimal>;
  unit_price: Generated<Decimal>;
  updated_at: Generated<Date>;
}

export interface InvProducts {
  company_id: string;
  created_at: Generated<Date>;
  id: Generated<number>;
  menuprod_id: number;
  product: string;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface InvProductSize {
  company_id: string;
  created_at: Generated<Date>;
  factor: Decimal | null;
  id: Generated<number>;
  is_ref: Generated<number | null>;
  menusize_id: number;
  size: string;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface InvPurchase {
  company_id: string | null;
  company_sap: string | null;
  created_at: Generated<Date>;
  created_by: Generated<string>;
  discount: Generated<Decimal>;
  /**
   * 1: Delivery por planeta, 2:Directo con el vendedor
   */
  gloss: string;
  id: Generated<number>;
  movepay_id: number | null;
  net_value: Decimal;
  num_guide: string | null;
  num_invoice: string | null;
  purchase_at: Date;
  /**
   * P: Comprar regular / E: Compra extraordinaria
   */
  purchase_type: Generated<string>;
  /**
   * 1: Nuevo; 2: Pendiente; 3: En proceso (comprando a tiendas); 4: En distribución; 5: Finalizado; 9: Extornado
   */
  status: Generated<number>;
  supplier_id: number;
  supplier_name: string;
  tax_value: Generated<Decimal>;
  total_value: Generated<Decimal>;
  updated_at: Generated<Date>;
  warehouse_id: string | null;
}

export interface InvPurchaseItem {
  created_at: Generated<Date>;
  id: Generated<number>;
  item_id: number;
  item_name: string;
  purchase_id: number;
  quantity: Generated<Decimal>;
  total_value: Generated<Decimal>;
  unit_value: Generated<Decimal>;
  updated_at: Generated<Date>;
}

export interface InvRecipeBase {
  company_id: string;
  created_at: Generated<Date>;
  id: Generated<number>;
  product_size_id: number | null;
  status: Generated<number>;
  title: string;
  updated_at: Generated<Date>;
}

export interface InvRecipemixBase {
  company_id: string;
  created_at: Generated<Date>;
  id: Generated<number>;
  item_id: number;
  measure_id: number | null;
  presentation_id: number | null;
  quantity: Generated<Decimal>;
  recipe_base_id: number;
  updated_at: Generated<Date>;
}

export interface InvRecipemixDetail {
  company_id: string;
  created_at: Generated<Date>;
  id: Generated<number>;
  item_id: number | null;
  measure_id: number | null;
  presentation_id: number | null;
  product_flavor_id: number;
  product_id: number;
  product_size_id: number;
  quantity: Generated<Decimal | null>;
  recipe_base_id: number | null;
  recipe_falvor_id: number | null;
  recipe_group: string;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface InvRecipemixFlavor {
  company_id: string;
  created_at: Generated<Date>;
  flavor_id: number;
  id: Generated<number>;
  item_id: number;
  measure_id: number | null;
  presentation_id: number | null;
  quantity: Generated<Decimal>;
  updated_at: Generated<Date>;
}

export interface InvStock {
  company_id: string | null;
  created_at: Generated<Date>;
  created_by: Generated<string>;
  id: Generated<number>;
  item_id: number;
  item_name: string;
  measure_id: number | null;
  quantity_in_dp: Generated<Decimal>;
  quantity_in_mv: Generated<Decimal>;
  quantity_in_pu: Generated<Decimal>;
  quantity_out_dp: Generated<Decimal>;
  quantity_out_mv: Generated<Decimal>;
  quantity_out_sl: Generated<Decimal>;
  /**
   * 0: anulado, 1: pendiente, 2: cerrado
   */
  status: Generated<number>;
  stock_at: Date;
  /**
   * stock teorico
   */
  stock_current: Generated<Decimal>;
  /**
   * stock dia anterior
   */
  stock_last: Generated<Decimal>;
  /**
   * stock conteo fisico
   */
  stock_physical: Generated<Decimal>;
  /**
   * stock valorizado del dia anterior
   */
  total_last: Generated<Decimal>;
  /**
   * stock valorizado del dia 
   */
  total_value: Generated<Decimal>;
  /**
   * valor unitario del dia
   */
  unit_value: Generated<Decimal>;
  updated_at: Generated<Date>;
  warehouse_id: string | null;
}

export interface InvSupplier {
  address: string | null;
  created_at: Generated<Date>;
  id: Generated<number>;
  legal_account_bco: string | null;
  legal_account_cci: string | null;
  legal_account_cur: string | null;
  legal_account_num: string | null;
  legal_account_type: string | null;
  legal_name: string | null;
  legal_number: string | null;
  /**
   * 1: Nuevo; 2: Pendiente y recibido; 3: En revisión; 4: En observación; 5: Alta; 9: Baja
   */
  status: Generated<number>;
  supplier: string;
  /**
   * M: Mercaderia; O: Otros
   */
  type_supplier: Generated<string | null>;
  updated_at: Generated<Date>;
}

export interface InvTmpltDispatch {
  created_at: Generated<Date | null>;
  id: Generated<number>;
  status: Generated<number>;
  /**
   * PIZZA,STEAK,PIZTEK
   */
  sucursal_type: string;
  updated_at: Generated<Date>;
  /**
   * D: Plantilla pedido de tienda, I: Plantilla inventario de tienda, W: Plantilla para almacen
   */
  used_to: string;
}

export interface InvTmpltDispatchItem {
  dispatch_id: number;
  id: Generated<number>;
  item_move_id: number;
  item_move_name: string;
  item_stock_id: number;
  item_stock_name: string;
  measure_id: number | null;
  quantity: Generated<Decimal>;
  total_value: Generated<Decimal>;
  unit_value: Generated<Decimal>;
}

export interface Parameters {
  created_at: Generated<Date>;
  id: Generated<number>;
  name: string;
  role: Generated<string>;
  status: Generated<number>;
  type: string;
  updated_at: Generated<Date>;
  value: string;
}

export interface RhAssistance {
  attendance_at: Date | null;
  company_id: string | null;
  created_at: Generated<Date>;
  employee_id: number | null;
  /**
   * ENTRADA; SALIDA; REFRI_SALE; REFRI_RETORNO
   */
  event: string | null;
  id: Generated<number>;
  pic_photo: string | null;
  status: Generated<number>;
  sucursal_id: string | null;
  updated_at: Generated<Date>;
}

export interface RhContract {
  company_id: string | null;
  contract_at: Date;
  created_at: Generated<Date>;
  employee_id: number;
  id: Generated<number>;
  jobtitle_id: number;
  salary: Generated<Decimal>;
  status: Generated<number>;
  sucursal_id: string | null;
  updated_at: Generated<Date>;
}

export interface RhEmployee {
  birthday_at: Date | null;
  created_at: Generated<Date>;
  doc_number: string;
  doc_type: string | null;
  email: string | null;
  first_name: string | null;
  /**
   * M: Masculino; F: Femenino
   */
  gender: string | null;
  id: Generated<number>;
  job_: string | null;
  /**
   * trabajo TIEMPO_COMPLETO, TIEMPO_PARCIAL,  EVENTUAL
   */
  job_mode: string | null;
  jobtitle_id: number | null;
  jobtitle_name: string | null;
  last_name: string | null;
  phone: string | null;
  pic_docb: string | null;
  pic_docf: string | null;
  pic_photo: string | null;
  status: Generated<number>;
  sucursal_id: string | null;
  updated_at: Generated<Date>;
}

export interface RhJobtitle {
  created_at: Generated<Date>;
  description: string | null;
  id: Generated<number>;
  status: Generated<number>;
  title: string;
  updated_at: Generated<Date>;
}

export interface RptVentadelivery {
  created_at: Generated<Date>;
  id: Generated<number>;
  priority: number | null;
  title: string;
  value: Decimal;
  venta_at: Date | null;
}

export interface SlsSucursalSales {
  created_at: Generated<Date>;
  created_by: Generated<string>;
  id: Generated<number>;
  sales_at: Date;
  sales_cash: Generated<Decimal>;
  sales_others: Generated<Decimal>;
  sales_pm: Generated<Decimal>;
  sales_total: Generated<Decimal>;
  store_id: string;
  updated_at: Generated<Date>;
}

export interface SysMenuReport {
  created_at: Generated<Date>;
  id: number;
  key_report: string | null;
  key_workspc: string | null;
  priority: Generated<number>;
  rpt_name: string | null;
  rpt_token: string | null;
  rpt_url: string | null;
  /**
   * 1:todos,2:solo web,3:solo app
   */
  show_in: Generated<number>;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface SysParameters {
  created_at: Generated<Date>;
  id: Generated<number>;
  name: string;
  role: Generated<string>;
  status: Generated<number>;
  type: string;
  updated_at: Generated<Date>;
  value: string;
}

export interface SysReportConfig {
  id: Generated<number>;
  rpt_account_flow: string | null;
  rpt_account_id: string | null;
  rpt_account_prior: number | null;
  rpt_group: string | null;
  rpt_name: string | null;
}

export interface SysReportEerr {
  eerr_from: Date | null;
  eerr_period: string | null;
  eerr_to: Date | null;
  id: Generated<number>;
}

export interface SysUploadLog {
  created_at: Generated<Date>;
  file_name: string | null;
  file_type: string | null;
  folder: string | null;
  id: Generated<number>;
  updated_at: Generated<Date>;
  upload_by: string | null;
}

export interface ZoldAccount {
  account: string;
  created_at: Generated<Date>;
  created_by: Generated<string>;
  father: string;
  id: string;
  is_father: Generated<number>;
  level: Generated<number>;
  status: Generated<number>;
  type: string;
  updated_at: Generated<Date>;
  visible: Generated<number>;
}

export interface ZoldAccountingItem {
  account_id: string;
  account_name: string | null;
  /**
   * Credito es Abono
   */
  amount_credit: Decimal | null;
  /**
   * Debito es Cargo
   */
  amount_debit: Decimal | null;
  cash_account_move_id: number | null;
  cash_lote_id: string | null;
  created_at: Generated<Date>;
  eerr_period: string | null;
  id: Generated<number>;
  move_id: number;
  updated_at: Generated<Date>;
}

export interface ZoldAccountingMove {
  copiedto_dw: Generated<number>;
  cost_center_id: number;
  created_at: Generated<Date>;
  created_by: Generated<string>;
  gloss: string;
  id: Generated<number>;
  move_at: Date;
  move_id: number | null;
  /**
   * C (Compra) 
   */
  move_type: string | null;
  num_doc: string | null;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface ZoldAdmCashAccount {
  account_id: string | null;
  codefis: string | null;
  created_at: Generated<Date>;
  id: Generated<number>;
  name: string;
  roles_id: number | null;
  status: string | null;
  sucursal_id: string | null;
  type_cash_id: number;
  updated_at: Generated<Date>;
}

export interface ZoldAdmCashAccountMove {
  account_flow: string | null;
  amount: Decimal | null;
  approved_at: Date | null;
  approved_by: string | null;
  cash_account_id: string | null;
  cash_account_id2: string | null;
  cash_flow: string | null;
  cash_id: number | null;
  category_account_id: string | null;
  category_expense_id: number | null;
  copiedto_dw: Generated<number>;
  created_at: Generated<Date>;
  created_by: string | null;
  days_id: Generated<number | null>;
  description: string | null;
  id: Generated<number>;
  rejected_at: Date | null;
  rejected_by: string | null;
  requested_at: Date | null;
  status: string;
  updated_at: Generated<Date>;
}

export interface ZoldAdmCashBalance {
  balance: Decimal | null;
  balance_at: Date | null;
  cash_account_id: number;
  cash_id: number | null;
  created_at: Generated<Date>;
  created_by: string | null;
  days_id: Generated<number | null>;
  id: Generated<number>;
  status_request: string | null;
}

export interface ZoldAdmCategoryExpense {
  account_flow: string | null;
  account_id: string | null;
  cash_flow: Generated<string | null>;
  codEfis: number | null;
  created_at: Generated<Date>;
  id: Generated<number>;
  m_order: number | null;
  name: string;
  roles_id: number | null;
  status: Generated<string>;
  type_category_id: number;
  /**
   * Ingreso Salida
   */
  type_mov: string | null;
  updated_at: Generated<Date>;
}

export interface ZoldAdmRequest {
  account_flow: string | null;
  amount: Decimal | null;
  amount_net: Decimal | null;
  amount_ret: Decimal | null;
  approved_at: Date | null;
  approved_by: string | null;
  cash_account_id: string | null;
  cash_id: number | null;
  cash_move: string | null;
  cash_ref_id: number | null;
  category_account_id: string | null;
  category_flow: string | null;
  category_id: number | null;
  category_move: string | null;
  copiedto_dw: Generated<number>;
  cost_center_id: number | null;
  created_at: Generated<Date>;
  created_by: string | null;
  days_id: Generated<number | null>;
  description: string | null;
  doc_url: string | null;
  id: Generated<number>;
  legal_name: string | null;
  legal_number: string | null;
  note: string | null;
  num_document: string | null;
  /**
   * CONTADO / CREDITO
   */
  pay_method: string | null;
  purchase_id: number | null;
  rejected_at: Date | null;
  rejected_by: string | null;
  request_main_id: number | null;
  request_type: string | null;
  requested_at: Date | null;
  retention: Generated<string | null>;
  status: Generated<string>;
  updated_at: Generated<Date>;
}

export interface ZoldBalance {
  account_id: string;
  balance_at: Date;
  balance_code: string | null;
  balance_credit: Generated<Decimal>;
  balance_debit: Generated<Decimal>;
  balance_last: Generated<Decimal>;
  balance_total: Generated<Decimal>;
  copiedto_dw: Generated<number>;
  created_at: Generated<Date>;
  created_by: Generated<string>;
  eerr_period: string | null;
  id: Generated<number>;
  updated_at: Generated<Date>;
}

export interface ZoldBusUnit {
  business: string;
  /**
   * clase negocio
   */
  class: string;
  created_at: Generated<Date>;
  external_code: string | null;
  id: Generated<number>;
  /**
   * correlativo
   */
  position: number;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface ZoldCostCenter {
  account_ajuste: string | null;
  account_caja: string | null;
  account_merca: string | null;
  created_at: Generated<Date>;
  id: Generated<number>;
  is_cash: Generated<number>;
  origin: string;
  status: Generated<number>;
  sucursal_id: string | null;
  updated_at: Generated<Date>;
}

export interface ZoldInvDispatchbase {
  created_at: Generated<Date>;
  id: Generated<number>;
  status: Generated<number>;
  /**
   * PIZZA,STEAK,PIZTEK
   */
  sucursal_type: string;
  updated_at: Generated<Date>;
  /**
   * D: Plantilla pedido de tienda, I: Plantilla inventario de tienda, W: Plantilla para almacen
   */
  used_to: string;
}

export interface ZoldInvDispatchbaseItem {
  dispatch_id: number;
  id: Generated<number>;
  item_move_id: number;
  item_move_name: string;
  item_stock_id: number;
  item_stock_name: string;
  measure_id: number | null;
  presentation_id: number;
  presentation_name: string;
  quantity: Generated<Decimal>;
  total_value: Generated<Decimal>;
  unit_value: Generated<Decimal>;
}

export interface ZoldSeatAccount {
  account_id: string;
  cod_ref: number | null;
  created_at: Generated<Date>;
  flow: string;
  id: Generated<number>;
  is_multiple: Generated<string>;
  seat_id: number;
  seat_number: Generated<number>;
  updated_at: Generated<Date>;
}

export interface ZoldSeatAuto {
  created_at: Generated<Date>;
  created_by: Generated<string>;
  id: Generated<number>;
  /**
   * 0: simple, 1: simple multiple, 2: multiple full
   */
  is_multiple: Generated<number>;
  seat: string;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface ZoldTypeCash {
  campox: Json | null;
  created_at: Generated<Date>;
  id: Generated<number>;
  name: string;
  status: string | null;
  type_id: string | null;
  updated_at: Generated<Date>;
}

export interface ZoldTypeCategory {
  created_at: Generated<Date>;
  id: Generated<number>;
  name: string;
  status: string | null;
  type_id: string | null;
  updated_at: Generated<Date>;
}

export interface DB {
  adm_company: AdmCompany;
  adm_payment_order: AdmPaymentOrder;
  adm_req_contract: AdmReqContract;
  adm_req_file: AdmReqFile;
  adm_req_log: AdmReqLog;
  adm_req_nondocs: AdmReqNondocs;
  adm_requirement: AdmRequirement;
  adm_sucursal: AdmSucursal;
  adm_sucursal_move: AdmSucursalMove;
  adm_terminalpos: AdmTerminalpos;
  bnk_reconciliation: BnkReconciliation;
  ext_pagos_culqi: ExtPagosCulqi;
  ext_pagos_izipay: ExtPagosIzipay;
  fin_account: FinAccount;
  fin_autoentry: FinAutoentry;
  fin_autoentry_item: FinAutoentryItem;
  fin_balance: FinBalance;
  fin_cashbank: FinCashbank;
  fin_cashbank_balance: FinCashbankBalance;
  fin_costcenter: FinCostcenter;
  fin_journalentry: FinJournalentry;
  fin_journalentry_item: FinJournalentryItem;
  fin_money_change: FinMoneyChange;
  fin_movetype: FinMovetype;
  iam_function: IamFunction;
  iam_log: IamLog;
  iam_module: IamModule;
  iam_permission: IamPermission;
  iam_role: IamRole;
  iam_user: IamUser;
  inv_brand: InvBrand;
  inv_carrier: InvCarrier;
  inv_category: InvCategory;
  inv_dispatch: InvDispatch;
  inv_dispatch_item: InvDispatchItem;
  inv_equivalence: InvEquivalence;
  inv_formula: InvFormula;
  inv_formula_product: InvFormulaProduct;
  inv_item: InvItem;
  inv_kardex: InvKardex;
  inv_measure: InvMeasure;
  inv_presentation: InvPresentation;
  inv_product: InvProduct;
  inv_product_flavor: InvProductFlavor;
  inv_product_size: InvProductSize;
  inv_production: InvProduction;
  inv_production_item: InvProductionItem;
  inv_products: InvProducts;
  inv_purchase: InvPurchase;
  inv_purchase_item: InvPurchaseItem;
  inv_recipe_base: InvRecipeBase;
  inv_recipemix_base: InvRecipemixBase;
  inv_recipemix_detail: InvRecipemixDetail;
  inv_recipemix_flavor: InvRecipemixFlavor;
  inv_stock: InvStock;
  inv_supplier: InvSupplier;
  inv_tmplt_dispatch: InvTmpltDispatch;
  inv_tmplt_dispatch_item: InvTmpltDispatchItem;
  parameters: Parameters;
  rh_assistance: RhAssistance;
  rh_contract: RhContract;
  rh_employee: RhEmployee;
  rh_jobtitle: RhJobtitle;
  rpt_ventadelivery: RptVentadelivery;
  sls_sucursal_sales: SlsSucursalSales;
  sys_menu_report: SysMenuReport;
  sys_parameters: SysParameters;
  sys_report_config: SysReportConfig;
  sys_report_eerr: SysReportEerr;
  sys_upload_log: SysUploadLog;
  zold_account: ZoldAccount;
  zold_accounting_item: ZoldAccountingItem;
  zold_accounting_move: ZoldAccountingMove;
  zold_adm_cash_account: ZoldAdmCashAccount;
  zold_adm_cash_account_move: ZoldAdmCashAccountMove;
  zold_adm_cash_balance: ZoldAdmCashBalance;
  zold_adm_category_expense: ZoldAdmCategoryExpense;
  zold_adm_request: ZoldAdmRequest;
  zold_balance: ZoldBalance;
  zold_bus_unit: ZoldBusUnit;
  zold_cost_center: ZoldCostCenter;
  zold_inv_dispatchbase: ZoldInvDispatchbase;
  zold_inv_dispatchbase_item: ZoldInvDispatchbaseItem;
  zold_seat_account: ZoldSeatAccount;
  zold_seat_auto: ZoldSeatAuto;
  zold_type_cash: ZoldTypeCash;
  zold_type_category: ZoldTypeCategory;
}
