/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Decimal = ColumnType<string, number | string>;

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Account {
  account: string;
  created_at: Generated<Date>;
  created_by: Generated<string>;
  father: string;
  id: string;
  is_father: Generated<number>;
  level: Generated<number>;
  status: Generated<number>;
  type: string;
  updated_at: Generated<Date>;
  visible: Generated<number>;
}

export interface AccountingItem {
  account_id: string;
  account_name: string | null;
  /**
   * Credito es Abono
   */
  amount_credit: Decimal | null;
  /**
   * Debito es Cargo
   */
  amount_debit: Decimal | null;
  cash_account_move_id: number | null;
  cash_lote_id: string | null;
  created_at: Generated<Date>;
  eerr_period: string | null;
  id: Generated<number>;
  move_id: number;
  updated_at: Generated<Date>;
}

export interface AccountingMove {
  copiedto_dw: Generated<number>;
  cost_center_id: number;
  created_at: Generated<Date>;
  created_by: Generated<string>;
  gloss: string;
  id: Generated<number>;
  move_at: Date;
  move_id: number | null;
  /**
   * C (Compra) 
   */
  move_type: string | null;
  num_doc: string | null;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface AdmCashAccount {
  account_id: string | null;
  codefis: string | null;
  created_at: Generated<Date>;
  id: Generated<number>;
  name: string;
  roles_id: number | null;
  status: string | null;
  sucursal_id: string | null;
  type_cash_id: number;
  updated_at: Generated<Date>;
}

export interface AdmCashAccountMove {
  account_flow: string | null;
  amount: Decimal | null;
  approved_at: Date | null;
  approved_by: string | null;
  cash_account_id: string | null;
  cash_account_id2: string | null;
  cash_flow: string | null;
  cash_id: number | null;
  category_account_id: string | null;
  category_expense_id: number | null;
  copiedto_dw: Generated<number>;
  created_at: Generated<Date>;
  created_by: string | null;
  days_id: Generated<number | null>;
  description: string | null;
  id: Generated<number>;
  rejected_at: Date | null;
  rejected_by: string | null;
  requested_at: Date | null;
  status: string;
  updated_at: Generated<Date>;
}

export interface AdmCashBalance {
  balance: Decimal | null;
  balance_at: Date | null;
  cash_account_id: number;
  cash_id: number | null;
  created_at: Generated<Date>;
  created_by: string | null;
  days_id: Generated<number | null>;
  id: Generated<number>;
  status_request: string | null;
}

export interface AdmCategoryExpense {
  account_flow: string | null;
  account_id: string | null;
  cash_flow: Generated<string | null>;
  codEfis: number | null;
  created_at: Generated<Date>;
  id: Generated<number>;
  m_order: number | null;
  name: string;
  roles_id: number | null;
  status: Generated<string>;
  type_category_id: number;
  /**
   * Ingreso Salida
   */
  type_mov: string | null;
  updated_at: Generated<Date>;
}

export interface AdmCompany {
  created_at: Generated<Date>;
  has_accounting: Generated<number>;
  id: string;
  nro_ruc: string | null;
  razon_social: string | null;
  status: Generated<number>;
  title: string;
  /**
   * C: Comercial, L: Logistica, O: Otros
   */
  type_company: Generated<string>;
  updated_at: Generated<Date>;
}

export interface AdmFile {
  created_at: Generated<Date>;
  created_by: string | null;
  doc_date: Date | null;
  doc_description: string | null;
  doc_number: string | null;
  doc_ocr: string | null;
  doc_request: number | null;
  doc_type: string | null;
  doc_url: string | null;
  id: Generated<number>;
}

export interface AdmRequest {
  account_flow: string | null;
  amount: Decimal | null;
  amount_net: Decimal | null;
  amount_ret: Decimal | null;
  approved_at: Date | null;
  approved_by: string | null;
  cash_account_id: string | null;
  cash_id: number | null;
  cash_move: string | null;
  cash_ref_id: number | null;
  category_account_id: string | null;
  category_flow: string | null;
  category_id: number | null;
  category_move: string | null;
  copiedto_dw: Generated<number>;
  cost_center_id: number | null;
  created_at: Generated<Date>;
  created_by: string | null;
  currency: Generated<string | null>;
  days_id: Generated<number | null>;
  description: string | null;
  doc_url: string | null;
  id: Generated<number>;
  legal_name: string | null;
  legal_number: string | null;
  note: string | null;
  num_document: string | null;
  /**
   * CONTADO / CREDITO
   */
  pay_method: string | null;
  purchase_id: number | null;
  rejected_at: Date | null;
  rejected_by: string | null;
  request_main_id: number | null;
  request_type: string | null;
  requested_at: Date | null;
  retention: Generated<string | null>;
  status: Generated<string>;
  updated_at: Generated<Date>;
}

export interface AdmSucursal {
  cfd_igv: Decimal | null;
  cfd_seql_bo: number | null;
  cfd_seql_de: number | null;
  cfd_seql_fa: number | null;
  cfd_seql_gr: number | null;
  cfd_serie_bo: string | null;
  cfd_serie_de: string | null;
  cfd_serie_fa: string | null;
  cfd_serie_gr: string | null;
  company_id: string | null;
  created_at: Generated<Date>;
  efact_pass: string | null;
  guide_template: string | null;
  id: string;
  legalperson_account_bco: string | null;
  legalperson_account_cci: string | null;
  legalperson_account_cur: string | null;
  legalperson_account_num: string | null;
  legalperson_account_type: string | null;
  legalperson_docnum: string | null;
  legalperson_doctype: string | null;
  legalperson_name: string | null;
  sede_nro_ruc: string | null;
  sede_razon_social: string | null;
  status: Generated<number>;
  title: string;
  /**
   * T: Tienda, A: Almacen, O: Oficina
   */
  type_sede: string | null;
  ubi_address: string | null;
  ubi_city: string | null;
  ubi_district: string | null;
  ubi_route: string | null;
  updated_at: Generated<Date>;
}

export interface AdmTerminalpos {
  created_at: Generated<Date>;
  id: Generated<number>;
  status: Generated<number>;
  sucursal_id: string | null;
  supplier: string | null;
  terminal: string;
  updated_at: Generated<Date>;
}

export interface AdmTrademark {
  created_at: Generated<Date>;
  id: string;
  title: string;
  updated_at: Generated<Date>;
}

export interface AdmTypeCash {
  created_at: Generated<Date>;
  id: Generated<number>;
  name: string;
  status: string | null;
  type_id: string | null;
  updated_at: Generated<Date>;
}

export interface AdmTypeCategory {
  created_at: Generated<Date>;
  id: Generated<number>;
  name: string;
  status: string | null;
  type_id: string | null;
  updated_at: Generated<Date>;
}

export interface Balance {
  account_id: string;
  balance_at: Date;
  balance_code: string | null;
  balance_credit: Generated<Decimal>;
  balance_debit: Generated<Decimal>;
  balance_last: Generated<Decimal>;
  balance_total: Generated<Decimal>;
  copiedto_dw: Generated<number>;
  created_at: Generated<Date>;
  created_by: Generated<string>;
  eerr_period: string | null;
  id: Generated<number>;
  updated_at: Generated<Date>;
}

export interface BnkReconciliation {
  bnk_agencia: string | null;
  bnk_fecha: Date | null;
  bnk_monto: Decimal | null;
  bnk_name: string | null;
  bnk_operacion_num: string | null;
  bnk_operacion_text: string | null;
  bnk_referencia: string | null;
  bnk_saldo: Decimal | null;
  bnk_usuario: string | null;
  bnk_utc: string | null;
  created_at: Generated<Date>;
  req_description: string | null;
  req_id: number | null;
  req_monto: Decimal | null;
  transactionkey: string;
  updated_at: Generated<Date>;
  updated_by: string | null;
}

export interface BusUnit {
  business: string;
  /**
   * clase negocio
   */
  class: string;
  created_at: Generated<Date>;
  external_code: string | null;
  id: Generated<number>;
  /**
   * correlativo
   */
  position: number;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface CostCenter {
  account_ajuste: string | null;
  account_caja: string | null;
  account_merca: string | null;
  created_at: Generated<Date>;
  id: Generated<number>;
  is_cash: Generated<number>;
  origin: string;
  status: Generated<number>;
  sucursal_id: string | null;
  updated_at: Generated<Date>;
}

export interface ExtPagosCulqi {
  apellidoscliente: string | null;
  apellidostarjeta: string | null;
  aplicacion: string | null;
  cashmove_id: string | null;
  ciudad: string | null;
  codigoautorizacion: string | null;
  codigoreferencia: string | null;
  codigorespuesta: string | null;
  comisionfijatotal: Decimal | null;
  comisionpropina: Decimal | null;
  comisiontotal: Decimal | null;
  comisionvariablepropina: Decimal | null;
  comisionvariabletotal: Decimal | null;
  comisionvariableventa: Decimal | null;
  comisionventa: Decimal | null;
  copiedto_dw: Generated<number>;
  correoelectronicocliente: string | null;
  correoelectronicotarjeta: string | null;
  created_at: Generated<Date>;
  descripcionproducto: string | null;
  devolucion: number | null;
  direccion: string | null;
  estado: string | null;
  fechadeabono: Date | null;
  fechadeabono_iso: string | null;
  fechadelatransaccion: Date | null;
  fechadelatransaccion_iso: string | null;
  fechadevolucion: Date | null;
  idcargo: string | null;
  idcliente: string | null;
  idventa: string | null;
  idvoucher: string | null;
  igvpropina: Decimal | null;
  igvtotal: Decimal | null;
  igvventa: Decimal | null;
  marca: string | null;
  moneda: string | null;
  montoabonofinal: Decimal | null;
  montoaproximadoabonopropina: Decimal | null;
  montoaproximadoabonototal: Decimal | null;
  montoaproximadoabonoventa: Decimal | null;
  montopropina: Decimal | null;
  montoventa: Decimal | null;
  nombrebanco: string | null;
  nombrescliente: string | null;
  nombrestarjeta: string | null;
  nropedido: string | null;
  nrotarjeta: string | null;
  pais: string | null;
  paisbanco: string | null;
  producto: string | null;
  requestpay_id: string | null;
  serieterminal: string | null;
  sucursalcode: string | null;
  sucursalnombre: string | null;
  telefono: string | null;
  terminal: string | null;
  ticket: string | null;
  tipopago: string | null;
  transactionkey: string;
  ult4digitos: string | null;
  ventafinaltotal: Decimal | null;
}

export interface ExtPagosIzipay {
  abonodelote: Decimal | null;
  cashmove_id: string | null;
  codigo: string | null;
  codigodeautorizacion: string | null;
  comision: Decimal | null;
  copiedto_dw: Generated<number>;
  created_at: Generated<Date>;
  cuotas: number | null;
  estado: string | null;
  fechadeabono: Date | null;
  fechadeabono_iso: string | null;
  fechadecierredelote: Date | null;
  fechadeproceso: Date | null;
  fechadetransaccion: Date | null;
  fechadetransaccion_iso: string | null;
  igv: Decimal | null;
  importe: Decimal | null;
  importeneto: Decimal | null;
  marcadetarjeta: string | null;
  moneda: string | null;
  numdelote: number | null;
  numderef: number | null;
  numdetarjeta: string | null;
  observaciones: string | null;
  requestpay_id: string | null;
  serieterminal: string | null;
  sucursalcode: string | null;
  sucursalnombre: string | null;
  terminal: string | null;
  tipodecaptura: string | null;
  tipodemovimiento: string | null;
  transaccion: string | null;
  transactionkey: string;
}

export interface IamFunction {
  created_at: Generated<Date>;
  function: string;
  id: Generated<number>;
  module_id: number | null;
  path_function: string | null;
  path_view: string | null;
  priority: number | null;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface IamLog {
  /**
   * LOGIN, CREATE, EDIT, DELETE, APPROVED, PAID
   */
  action: string | null;
  created_at: Generated<Date>;
  id: Generated<number>;
  module_id: number | null;
  module_name: string | null;
  tbl_name: string | null;
  tbl_primary_id: string | null;
  user_email: string | null;
  user_id: number | null;
  user_name: string | null;
}

export interface IamModule {
  created_at: Generated<Date>;
  id: Generated<number>;
  module: string;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface IamPermission {
  function_id: number | null;
  granted: number | null;
  id: Generated<number>;
  module_id: number | null;
  role_id: number | null;
}

export interface IamRole {
  created_at: Generated<Date>;
  id: Generated<number>;
  role: string;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface IamUser {
  created_at: Generated<Date>;
  email: string;
  email_token: string | null;
  email_validate: Generated<string>;
  id: Generated<number>;
  name: string;
  password: string;
  phone: string | null;
  role_id: number | null;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface InvBrand {
  brand: string;
  code: string | null;
  created_at: Generated<Date>;
  id: Generated<number>;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface InvCarrier {
  carrier_name: string;
  /**
   * transportista nro de doc 
   */
  carrier_nro_doc: string | null;
  /**
   * razon social transportista
   */
  carrier_razon_social: string | null;
  /**
   * transportista tipo de doc
   */
  carrier_tipo_doc: Generated<string | null>;
  /**
   * conductor apellidos
   */
  conductor_apellidos: string | null;
  /**
   * conductor nombres
   */
  conductor_nombres: string | null;
  /**
   * nro de doc conductor
   */
  conductor_nro_doc: string | null;
  /**
   * nro de licencia de conductor
   */
  conductor_nro_licencia: string | null;
  /**
   * tipo de conductor
   */
  conductor_tipo: string | null;
  /**
   * tipo de doc de conductor
   */
  conductor_tipo_doc: string | null;
  created_at: Generated<Date>;
  id: Generated<number>;
  /**
   * 1: Nuevo; 2: Pendiente y recibido; 3: En revisión; 4: En observación; 5: Alta; 9: Baja
   */
  status: Generated<number>;
  /**
   * nro de placa de vehiculo principal
   */
  transporte_nro_placa: string | null;
  updated_at: Generated<Date>;
}

export interface InvCategory {
  category: string;
  created_at: Generated<Date>;
  id: Generated<number>;
  priority: Generated<number>;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface InvDispatch {
  approved_by: string | null;
  company_id: string | null;
  /**
   * conductor apellidos
   */
  conductor_apellidos: string | null;
  /**
   * conductor nombres
   */
  conductor_nombres: string | null;
  /**
   * nro de doc conductor
   */
  conductor_nro_doc: string | null;
  /**
   * nro de licencia de conductor
   */
  conductor_nro_licencia: string | null;
  /**
   * tipo de conductor
   */
  conductor_tipo: string | null;
  /**
   * tipo de doc de conductor
   */
  conductor_tipo_doc: string | null;
  created_at: Generated<Date>;
  created_by: Generated<string>;
  detra_value: Generated<Decimal>;
  doc_url: string | null;
  gloss: string | null;
  has_detraction: Generated<number>;
  id: Generated<number>;
  move_at: Date;
  /**
   * D: Despacho almacen -tienda / M: Movimiento entre tiendas / E: Despacho excepcional
   */
  move_type: Generated<string>;
  net_value: Generated<Decimal>;
  num_guide: string | null;
  num_invoice: string | null;
  requested_by: string | null;
  /**
   * 1: Nuevo pedido por la tienda; 2: Aprobado por almacen; 3: Recibido por la tienda; 0: Anulado
   */
  status: Generated<number>;
  sucursal_from_id: string;
  sucursal_to_id: string | null;
  tax_value: Generated<Decimal>;
  total_value: Generated<Decimal>;
  /**
   * transportista nro de doc 
   */
  transporte_nro_doc: string | null;
  /**
   * nro de placa de vehiculo principal
   */
  transporte_nro_placa: string | null;
  /**
   * razon social transportista
   */
  transporte_razon_social: string | null;
  /**
   * transportista tipo de doc
   */
  transporte_tipo_doc: Generated<string | null>;
  updated_at: Generated<Date>;
}

export interface InvDispatchbase {
  created_at: Generated<Date>;
  id: Generated<number>;
  status: Generated<number>;
  /**
   * PIZZA,STEAK,PIZTEK
   */
  sucursal_type: string;
  updated_at: Generated<Date>;
  /**
   * D: Plantilla pedido de tienda, I: Plantilla inventario de tienda, W: Plantilla para almacen
   */
  used_to: string;
}

export interface InvDispatchbaseItem {
  dispatch_id: number;
  id: Generated<number>;
  item_move_id: number;
  item_move_name: string;
  item_stock_id: number;
  item_stock_name: string;
  measure_id: number | null;
  presentation_id: number;
  presentation_name: string;
  quantity: Generated<Decimal>;
  total_value: Generated<Decimal>;
  unit_value: Generated<Decimal>;
}

export interface InvDispatchItem {
  created_at: Generated<Date>;
  dispatch_id: number;
  id: Generated<number>;
  item_id: number;
  item_name: string;
  measure_id: number | null;
  /**
   * peso bruto
   */
  peso_bruto: Generated<Decimal | null>;
  quantity: Generated<Decimal>;
  total_value: Generated<Decimal>;
  /**
   * modalidad traslado: 01(si es publico) o 02 (privado)
   */
  transport_mode: string | null;
  unit_value: Generated<Decimal>;
  updated_at: Generated<Date>;
  weight: Generated<Decimal>;
}

export interface InvEquivalence {
  created_at: Generated<Date>;
  id: Generated<number>;
  measure_id: number;
  presentation_from: number;
  presentation_to: number | null;
  status: Generated<number>;
  updated_at: Generated<Date>;
  value_factor: Generated<Decimal>;
  value_from: Generated<Decimal>;
}

export interface InvFormula {
  created_at: Generated<Date>;
  formula: string;
  id: Generated<number>;
  measure_id: number | null;
  performance: number;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface InvFormulaProduct {
  created_at: Generated<Date>;
  formula_id: number;
  id: Generated<number>;
  item_id: number;
  item_name: string;
  measure_id: number | null;
  presentation_id: number;
  presentation_name: string;
  quantity: Generated<Decimal>;
  updated_at: Generated<Date>;
}

export interface InvItem {
  brand_id: number;
  category_id: number | null;
  created_at: Generated<Date>;
  has_detraction: Generated<number>;
  id: Generated<number>;
  item_code: Generated<string>;
  item_name: string;
  /**
   * O: Item de origen / D: Item derivado
   */
  item_type: Generated<string>;
  /**
   * D: Item venta directa, T: Ingrediente
   */
  item_used_to: string | null;
  measure_id: number | null;
  old_product_id: number | null;
  presentation_id: number;
  /**
   * 1: Nuevo; 2: Pendiente y recibido; 3: En revisión; 4: En observación; 5: Alta; 9: Baja
   */
  status: Generated<number>;
  subcategory_id: number | null;
  supplier_id: number;
  unit_cost: Generated<Decimal>;
  unit_price: Generated<Decimal>;
  updated_at: Generated<Date>;
}

export interface InvKardex {
  company_id: string | null;
  created_at: Generated<Date>;
  created_by: Generated<string>;
  id: Generated<number>;
  item_id: number;
  item_name: string;
  move_at: Date;
  /**
   * E entrada S salida
   */
  move_flow: string;
  move_id: number;
  /**
   * C compra / P produccion / D despacho / I Carga_ini
   */
  move_type: string;
  num_doc: string | null;
  quantity: Generated<Decimal>;
  /**
   * stock actual
   */
  stock_current: Generated<Decimal>;
  /**
   * ultimo stock
   */
  stock_last: Generated<Decimal>;
  total_current: Generated<Decimal>;
  total_last: Generated<Decimal>;
  /**
   * total precio venta
   */
  total_price: Generated<Decimal>;
  /**
   * 01 Factura; 03 Boleta; 04 Ticket de Salida; 07 Nota de crédito; 08 Nota de débito; 09 Guia remisión; 31 Guia transportista
   */
  type_doc: string | null;
  /**
   * precio venta
   */
  unit_price: Generated<Decimal>;
  /**
   * precio compra
   */
  unit_purchase: Generated<Decimal>;
  updated_at: Generated<Date>;
  warehouse_id: string | null;
}

export interface InvMeasure {
  code: string | null;
  created_at: Generated<Date>;
  id: Generated<number>;
  measure: string;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface InvPresentation {
  created_at: Generated<Date>;
  id: Generated<number>;
  presentation: string;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface InvProduct {
  category_id: number | null;
  created_at: Generated<Date>;
  external_code: string | null;
  formula_id: number | null;
  id: Generated<number>;
  measure_id: number | null;
  product: string;
  /**
   * 1: Nuevo; 2: Pendiente y recibido; 3: En revisión; 4: En observación; 5: Disponible; 9: Caducado
   */
  status: Generated<number>;
  unit_price: Decimal | null;
  updated_at: Generated<Date>;
}

export interface InvProduction {
  created_at: Generated<Date>;
  created_by: Generated<string>;
  discount: Generated<Decimal>;
  formula_id: number;
  formula_name: string;
  id: Generated<number>;
  measure_id: number | null;
  net_value: Generated<Decimal>;
  production_at: Date;
  quantity: Generated<Decimal>;
  /**
   * 1: Nuevo; 2: Pendiente; 3: En proceso (comprando a tiendas); 4: En distribución; 5: Finalizado; 9: Extornado
   */
  status: Generated<number>;
  tax_value: Generated<Decimal>;
  total_value: Generated<Decimal>;
  unit_value: Generated<Decimal>;
  updated_at: Generated<Date>;
}

export interface InvProductionItem {
  created_at: Generated<Date>;
  id: Generated<number>;
  item_id: number;
  item_name: string;
  measure_id: number | null;
  presentation_id: number;
  presentation_name: string;
  production_id: number;
  quantity: Generated<Decimal>;
  total_value: Generated<Decimal>;
  unit_price: Generated<Decimal>;
  updated_at: Generated<Date>;
}

export interface InvProductSize {
  company_id: string;
  created_at: Generated<Date>;
  factor: Decimal | null;
  id: Generated<number>;
  is_ref: Generated<number | null>;
  menusize_id: number;
  size: string;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface InvPurchase {
  company_id: string | null;
  company_sap: string | null;
  created_at: Generated<Date>;
  created_by: Generated<string>;
  discount: Generated<Decimal>;
  /**
   * 1: Delivery por planeta, 2:Directo con el vendedor
   */
  gloss: string;
  id: Generated<number>;
  movepay_id: number | null;
  net_value: Decimal;
  num_guide: string | null;
  num_invoice: string | null;
  purchase_at: Date;
  /**
   * P: Comprar regular / E: Compra extraordinaria
   */
  purchase_type: Generated<string>;
  /**
   * 1: Nuevo; 2: Pendiente; 3: En proceso (comprando a tiendas); 4: En distribución; 5: Finalizado; 9: Extornado
   */
  status: Generated<number>;
  supplier_id: number;
  supplier_name: string;
  tax_value: Generated<Decimal>;
  total_value: Generated<Decimal>;
  updated_at: Generated<Date>;
  warehouse_id: string | null;
}

export interface InvPurchaseItem {
  created_at: Generated<Date>;
  id: Generated<number>;
  item_id: number;
  item_name: string;
  purchase_id: number;
  quantity: Generated<Decimal>;
  total_value: Generated<Decimal>;
  unit_value: Generated<Decimal>;
  updated_at: Generated<Date>;
}

export interface InvStock {
  company_id: string | null;
  created_at: Generated<Date>;
  created_by: Generated<string>;
  id: Generated<number>;
  item_id: number;
  item_name: string;
  measure_id: number | null;
  quantity_in_dp: Generated<Decimal>;
  quantity_in_mv: Generated<Decimal>;
  quantity_in_pu: Generated<Decimal>;
  quantity_out_dp: Generated<Decimal>;
  quantity_out_mv: Generated<Decimal>;
  quantity_out_sl: Generated<Decimal>;
  /**
   * 0: anulado, 1: pendiente, 2: cerrado
   */
  status: Generated<number>;
  stock_at: Date;
  /**
   * stock teorico
   */
  stock_current: Generated<Decimal>;
  /**
   * stock dia anterior
   */
  stock_last: Generated<Decimal>;
  /**
   * stock conteo fisico
   */
  stock_physical: Generated<Decimal>;
  /**
   * stock valorizado del dia anterior
   */
  total_last: Generated<Decimal>;
  /**
   * stock valorizado del dia 
   */
  total_value: Generated<Decimal>;
  /**
   * valor unitario del dia
   */
  unit_value: Generated<Decimal>;
  updated_at: Generated<Date>;
  warehouse_id: string | null;
}

export interface InvSubcategory {
  category_id: number | null;
  created_at: Generated<Date>;
  has_detraction: Generated<number>;
  id: Generated<number>;
  measure_id: number | null;
  /**
   * 1: Nuevo; 2: Pendiente y recibido; 3: En revisión; 4: En observación; 5: Disponible; 9: Caducado
   */
  status: Generated<number>;
  subcategory: string;
  updated_at: Generated<Date>;
}

export interface InvSupplier {
  address: string | null;
  bank_account_cci: string | null;
  bank_account_mny: string | null;
  bank_account_num: string | null;
  bank_account_type: string | null;
  bank_code: string | null;
  bank_name: string | null;
  created_at: Generated<Date>;
  id: Generated<number>;
  legal_name: string | null;
  legal_number: string | null;
  /**
   * 1: Nuevo; 2: Pendiente y recibido; 3: En revisión; 4: En observación; 5: Alta; 9: Baja
   */
  status: Generated<number>;
  supplier: string;
  /**
   * M: Mercaderia; O: Otros
   */
  type_supplier: Generated<string | null>;
  updated_at: Generated<Date>;
}

export interface InvTmpltDispatch {
  created_at: Generated<Date | null>;
  id: Generated<number>;
  status: Generated<number>;
  /**
   * PIZZA,STEAK,PIZTEK
   */
  sucursal_type: string;
  updated_at: Generated<Date>;
  /**
   * D: Plantilla pedido de tienda, I: Plantilla inventario de tienda, W: Plantilla para almacen
   */
  used_to: string;
}

export interface InvTmpltDispatchItem {
  dispatch_id: number;
  id: Generated<number>;
  item_move_id: number;
  item_move_name: string;
  item_stock_id: number;
  item_stock_name: string;
  measure_id: number | null;
  quantity: Generated<Decimal>;
  total_value: Generated<Decimal>;
  unit_value: Generated<Decimal>;
}

export interface Kardex {
  created_at: Generated<Date>;
  created_by: Generated<string>;
  id: Generated<number>;
  measure_id: number | null;
  move_at: Date | null;
  /**
   * E entrada S salida
   */
  move_flow: string;
  move_id: number;
  /**
   * C compra / P produccion / D despacho / I Carga_ini
   */
  move_type: string;
  num_doc: string | null;
  product_id: number;
  quantity: Decimal;
  stock_current: Generated<Decimal>;
  stock_last: Generated<Decimal>;
  total_price: Generated<Decimal>;
  type_doc: string | null;
  unit_price: Generated<Decimal>;
  unit_purchase: Generated<Decimal>;
  updated_at: Generated<Date>;
}

export interface LogProcess {
  prc_bucle: number | null;
  prc_key: string | null;
  prc_name: string | null;
  prc_step: number | null;
  prc_time: Date | null;
}

export interface Measure {
  code: string;
  created_at: Generated<Date>;
  id: Generated<number>;
  measure: string;
  status: number;
  updated_at: Generated<Date>;
}

export interface Parameters {
  created_at: Generated<Date>;
  id: Generated<number>;
  name: string;
  role: Generated<string>;
  status: Generated<number>;
  type: string;
  updated_at: Generated<Date>;
  value: string;
}

export interface Product {
  category_id: number | null;
  created_at: Generated<Date>;
  external_code: string | null;
  formula_id: number | null;
  id: Generated<number>;
  measure_id: number | null;
  name: string;
  /**
   * 1: Nuevo; 2: Pendiente y recibido; 3: En revisión; 4: En observación; 5: Disponible; 9: Caducado\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n
   */
  status: Generated<number>;
  unit_price: Decimal | null;
  updated_at: Generated<Date>;
}

export interface ProductCategory {
  category: string;
  created_at: Generated<Date>;
  id: Generated<number>;
  priority: Generated<number>;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface Purchase {
  company_sap: string | null;
  created_at: Generated<Date>;
  created_by: Generated<string>;
  discount: Generated<Decimal>;
  /**
   * 1: Delivery por planeta, 2:Directo con el vendedor
   */
  gloss: string;
  id: Generated<number>;
  movepay_id: number | null;
  net_value: Decimal;
  num_guide: string | null;
  num_invoice: string | null;
  purchase_at: Date;
  /**
   * 1: Nuevo; 2: Pendiente; 3: En proceso (comprando a tiendas); 4: En distribución; 5: Finalizado; 9: Extornado\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n
   */
  status: Generated<number>;
  supplier_id: number;
  supplier_name: string;
  tax_value: Generated<Decimal>;
  total_value: Generated<Decimal>;
  updated_at: Generated<Date>;
}

export interface PurchaseItem {
  created_at: Generated<Date>;
  id: Generated<number>;
  measure_id: number | null;
  product_id: number;
  product_name: string;
  purchase_id: number;
  quantity: Decimal;
  total_value: Generated<Decimal>;
  unit_value: Generated<Decimal>;
  updated_at: Generated<Date>;
}

export interface RhAssistance {
  attendance_at: Date | null;
  created_at: Generated<Date>;
  employee_id: number | null;
  /**
   * ENTRADA; SALIDA; REFRI_SALE; REFRI_RETORNO
   */
  event: string | null;
  id: Generated<number>;
  pic_photo: string | null;
  status: Generated<number>;
  sucursal_id: string | null;
  updated_at: Generated<Date>;
}

export interface RhContract {
  contract_at: Date;
  created_at: Generated<Date>;
  employee_id: number;
  id: Generated<number>;
  jobtitle_id: number;
  salary: Generated<Decimal>;
  status: Generated<number>;
  sucursal_id: string | null;
  updated_at: Generated<Date>;
}

export interface RhEmployee {
  birthday_at: Date | null;
  created_at: Generated<Date>;
  doc_number: string;
  doc_type: string | null;
  email: string | null;
  first_name: string | null;
  /**
   * M: Masculino; F: Femenino
   */
  gender: string | null;
  id: Generated<number>;
  job_mode: string | null;
  jobtitle_id: number | null;
  jobtitle_name: string | null;
  last_name: string | null;
  phone: string | null;
  pic_docb: string | null;
  pic_docf: string | null;
  pic_photo: string | null;
  status: Generated<number>;
  sucursal_id: string | null;
  updated_at: Generated<Date>;
}

export interface RhJobtitle {
  created_at: Generated<Date>;
  description: string | null;
  id: Generated<number>;
  name: string;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface RptVentadelivery {
  created_at: Generated<Date>;
  id: Generated<number>;
  priority: number | null;
  title: string;
  value: Decimal;
  venta_at: Date | null;
}

export interface SeatAccount {
  account_id: string;
  cod_ref: number | null;
  created_at: Generated<Date>;
  flow: string;
  id: Generated<number>;
  is_multiple: Generated<string>;
  seat_id: number;
  seat_number: Generated<number>;
  updated_at: Generated<Date>;
}

export interface SeatAuto {
  created_at: Generated<Date>;
  created_by: Generated<string>;
  id: Generated<number>;
  /**
   * 0: simple, 1: simple multiple, 2: multiple full
   */
  is_multiple: Generated<number>;
  seat: string;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface SlsItemSales {
  id: Generated<number>;
  item_id: number;
  item_name: string;
  prod_final_id: number;
  prod_final_name: string;
  prod_final_size: string | null;
  quantity_item: Generated<Decimal>;
  quantity_prod_final: Generated<Decimal>;
  sales_at: Date;
}

export interface SlsSucursalSales {
  created_at: Generated<Date>;
  created_by: Generated<string>;
  id: Generated<number>;
  sales_at: Date;
  sales_cash: Generated<Decimal>;
  sales_others: Generated<Decimal>;
  sales_pm: Generated<Decimal>;
  sales_total: Generated<Decimal>;
  store_id: string;
  updated_at: Generated<Date>;
}

export interface Stock {
  created_at: Generated<Date>;
  created_by: Generated<string>;
  id: Generated<number>;
  measure_id: number | null;
  product_id: number;
  quantity_in: Generated<Decimal>;
  quantity_out: Generated<Decimal>;
  stock_at: Date;
  stock_current: Generated<Decimal>;
  stock_last: Generated<Decimal>;
  total_value: Generated<Decimal>;
  unit_value: Generated<Decimal>;
  updated_at: Generated<Date>;
}

export interface SysMenuReport {
  created_at: Generated<Date>;
  id: number;
  key_report: string | null;
  key_workspc: string | null;
  priority: Generated<number>;
  rpt_name: string | null;
  rpt_token: string | null;
  rpt_url: string | null;
  /**
   * 1:todos,2:solo web,3:solo app
   */
  show_in: Generated<number>;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface SysParameters {
  created_at: Generated<Date>;
  id: Generated<number>;
  name: string;
  role: Generated<string>;
  status: Generated<number>;
  type: string;
  updated_at: Generated<Date>;
  value: string;
}

export interface SysReportConfig {
  id: Generated<number>;
  rpt_account_flow: string | null;
  rpt_account_id: string | null;
  rpt_account_prior: number | null;
  rpt_group: string | null;
  rpt_name: string | null;
}

export interface SysReportEerr {
  eerr_from: Date | null;
  eerr_period: string | null;
  eerr_to: Date | null;
  id: Generated<number>;
}

export interface SysUploadLog {
  created_at: Generated<Date>;
  file_name: string | null;
  file_type: string | null;
  folder: string | null;
  id: Generated<number>;
  updated_at: Generated<Date>;
  upload_by: string | null;
}

export interface UserAdmin {
  created_at: Generated<Date>;
  email: string;
  email_token: string | null;
  email_validate: Generated<string>;
  id: Generated<number>;
  name: string;
  password: string;
  /**
   * USR
   */
  role: string;
  status: Generated<number>;
  updated_at: Generated<Date>;
}

export interface ViewRedAccountmove {
  account_father_id: string;
  account_father_name: string | null;
  account_id: string;
  account_is_father: Generated<number>;
  account_level: Generated<number>;
  account_name: string;
  account_type: string;
  /**
   * Credito es Abono
   */
  amount_credit: Decimal | null;
  /**
   * Debito es Cargo
   */
  amount_debit: Decimal | null;
  balance_code: string | null;
  copiedto_dw: Generated<number>;
  cost_center_id: Generated<number | null>;
  cost_center_name: string | null;
  created_by: Generated<string>;
  gloss: string;
  is_cash: Generated<number | null>;
  move_at: Date;
  move_id: number | null;
  /**
   * C (Compra) 
   */
  move_type: string | null;
  num_doc: string | null;
  status: Generated<number>;
  transaction_key: string | null;
}

export interface ViewRedBalance {
  account_father: string;
  account_id: string;
  account_is_father: Generated<number>;
  account_level: Generated<number>;
  account_name: string;
  account_type: string;
  balance_at: Date;
  balance_code: string | null;
  balance_credit: Generated<Decimal>;
  balance_debit: Generated<Decimal>;
  balance_last: Generated<Decimal>;
  balance_total: Generated<Decimal>;
  copiedto_dw: Generated<number>;
  eerr_from: Date | null;
  eerr_period: string | null;
  eerr_to: Date | null;
  rpt_account_flow: string | null;
  rpt_account_prior: number | null;
  rpt_group: string | null;
}

export interface ViewRedCashmove {
  account_flow: string | null;
  amount: Decimal | null;
  amount_net: Decimal | null;
  amount_ret: Generated<number>;
  approved_at: Date | null;
  approved_by: string | null;
  cash_account_id: string | null;
  cash_id: number | null;
  cash_name: string | null;
  cash_type: Generated<string>;
  cash_type_name: Generated<string>;
  category_account_id: string | null;
  category_expense_id: number | null;
  category_move: Generated<string>;
  category_name: string;
  copiedto_dw: Generated<number | null>;
  cost_center_id: Generated<number | null>;
  cost_center_name: string | null;
  created_at: Generated<Date | null>;
  created_by: string | null;
  description: Generated<string>;
  doc_url: Generated<string>;
  legal_name: Generated<string>;
  legal_number: Generated<string>;
  num_document: Generated<string>;
  requested_at: Date | null;
  retention: Generated<number>;
  status: string | null;
  sucursal_code: string | null;
  sucursal_name: string | null;
  transaction_key: string | null;
}

export interface ViewRedRequest {
  account_flow: string | null;
  amount: Decimal | null;
  amount_net: Decimal | null;
  amount_ret: Decimal | null;
  approved_at: Date | null;
  approved_by: string | null;
  cash_account_id: string | null;
  cash_id: number | null;
  cash_name: Generated<string>;
  category_account_id: string | null;
  category_id: number | null;
  category_move: string | null;
  category_name: Generated<string>;
  copiedto_dw: Generated<number>;
  cost_center_id: number | null;
  cost_center_name: string | null;
  created_at: Generated<Date>;
  created_by: string | null;
  description: string | null;
  doc_url: string | null;
  legal_name: string | null;
  legal_number: string | null;
  num_document: string | null;
  request_type: string | null;
  request_type_name: string | null;
  requested_at: Date | null;
  retention: string | null;
  status: Generated<string>;
  sucursal_code: string | null;
  sucursal_name: string | null;
  transaction_key: Generated<string>;
}

export interface ViewRptStockVentaxTienda {
  Consumo: Decimal | null;
  Despacho: Decimal | null;
  Fecha: string | null;
  IdTienda: string;
  InTienda: Decimal | null;
  IvFinal: Decimal | null;
  IvInicial: Decimal | null;
  OutTienda: Decimal | null;
  Tienda: string;
  Venta: Decimal | null;
}

export interface Xaccount {
  account: string;
  created_at: Generated<Date>;
  created_by: Generated<string>;
  father: string;
  id: string;
  is_father: Generated<number>;
  level: Generated<number>;
  status: Generated<number>;
  type: string;
  updated_at: Generated<Date>;
  visible: Generated<number>;
}

export interface XadmSaldosCaja {
  cash_acccount_id: string | null;
  move_at: string | null;
  sum_caja: Decimal | null;
  sum_conta: Decimal | null;
}

export interface XoldSupplier {
  address: string | null;
  created_at: Generated<Date>;
  id: Generated<number>;
  legal_account_bco: string | null;
  legal_account_cci: string | null;
  legal_account_cur: string | null;
  legal_account_num: string | null;
  legal_account_type: string | null;
  legal_name: string | null;
  legal_number: string | null;
  /**
   * 1: Nuevo; 2: Pendiente y recibido; 3: En revisión; 4: En observación; 5: Alta; 9: Baja
   */
  status: Generated<number>;
  supplier: string;
  updated_at: Generated<Date>;
}

export interface DB {
  account: Account;
  accounting_item: AccountingItem;
  accounting_move: AccountingMove;
  adm_cash_account: AdmCashAccount;
  adm_cash_account_move: AdmCashAccountMove;
  adm_cash_balance: AdmCashBalance;
  adm_category_expense: AdmCategoryExpense;
  adm_company: AdmCompany;
  adm_file: AdmFile;
  adm_request: AdmRequest;
  adm_sucursal: AdmSucursal;
  adm_terminalpos: AdmTerminalpos;
  adm_trademark: AdmTrademark;
  adm_type_cash: AdmTypeCash;
  adm_type_category: AdmTypeCategory;
  balance: Balance;
  bnk_reconciliation: BnkReconciliation;
  bus_unit: BusUnit;
  cost_center: CostCenter;
  ext_pagos_culqi: ExtPagosCulqi;
  ext_pagos_izipay: ExtPagosIzipay;
  iam_function: IamFunction;
  iam_log: IamLog;
  iam_module: IamModule;
  iam_permission: IamPermission;
  iam_role: IamRole;
  iam_user: IamUser;
  inv_brand: InvBrand;
  inv_carrier: InvCarrier;
  inv_category: InvCategory;
  inv_dispatch: InvDispatch;
  inv_dispatch_item: InvDispatchItem;
  inv_dispatchbase: InvDispatchbase;
  inv_dispatchbase_item: InvDispatchbaseItem;
  inv_equivalence: InvEquivalence;
  inv_formula: InvFormula;
  inv_formula_product: InvFormulaProduct;
  inv_item: InvItem;
  inv_kardex: InvKardex;
  inv_measure: InvMeasure;
  inv_presentation: InvPresentation;
  inv_product: InvProduct;
  inv_product_size: InvProductSize;
  inv_production: InvProduction;
  inv_production_item: InvProductionItem;
  inv_purchase: InvPurchase;
  inv_purchase_item: InvPurchaseItem;
  inv_stock: InvStock;
  inv_subcategory: InvSubcategory;
  inv_supplier: InvSupplier;
  inv_tmplt_dispatch: InvTmpltDispatch;
  inv_tmplt_dispatch_item: InvTmpltDispatchItem;
  kardex: Kardex;
  log_process: LogProcess;
  measure: Measure;
  parameters: Parameters;
  product: Product;
  product_category: ProductCategory;
  purchase: Purchase;
  purchase_item: PurchaseItem;
  rh_assistance: RhAssistance;
  rh_contract: RhContract;
  rh_employee: RhEmployee;
  rh_jobtitle: RhJobtitle;
  rpt_ventadelivery: RptVentadelivery;
  seat_account: SeatAccount;
  seat_auto: SeatAuto;
  sls_item_sales: SlsItemSales;
  sls_sucursal_sales: SlsSucursalSales;
  stock: Stock;
  sys_menu_report: SysMenuReport;
  sys_parameters: SysParameters;
  sys_report_config: SysReportConfig;
  sys_report_eerr: SysReportEerr;
  sys_upload_log: SysUploadLog;
  user_admin: UserAdmin;
  view_red_accountmove: ViewRedAccountmove;
  view_red_balance: ViewRedBalance;
  view_red_cashmove: ViewRedCashmove;
  view_red_request: ViewRedRequest;
  view_rpt_stock_ventax_tienda: ViewRptStockVentaxTienda;
  xaccount: Xaccount;
  xadm_saldos_caja: XadmSaldosCaja;
  xold_supplier: XoldSupplier;
}
