/* eslint-disable unused-imports/no-unused-vars */
import { eachDayOfInterval, format, parseISO } from 'date-fns'
import { In, Raw, Repository } from 'typeorm'

import { InvStock } from 'pizzadb'
import { AppDataSource } from '../../../../config/database'
import { invStockRepository } from '../../../../repositories/inventory/invStock.repository'
import { productItemRepository } from '../../../../repositories/inventory/item.repository'
import { StockItemToCreateDto } from '../../dto'
import { STOCK_STATUS, StockGeneral } from '../../entities'
import { Item } from '../../entities/item'
import { ItemRepository } from '../../entities/repositories/item.repository'
import { StockRepository } from '../../entities/repositories/stock.repository'
import { TemplateRepository } from '../../entities/repositories/template.repository'
import { WarehousesRepository } from '../../entities/repositories/warehouses.repository'
import { calculateCurrent } from '../../entities/util'
import { WAREHOUSE_TYPE } from '../../entities/warehouse'

export class StockRepositoryImpl implements StockRepository {
  private readonly calculateCurrent = calculateCurrent
  constructor(
    private readonly templateRepository: TemplateRepository,
    private readonly warehouseRepository: WarehousesRepository,
    private readonly itemRepository: ItemRepository,
    private readonly stockRepository: Repository<InvStock>,
  ) {}

  async getLastInfoWarehouse(warehouseCode: string): Promise<{
    lastClosed: string | null
    warehouseName: string
    isWarehouse: boolean
  }> {
    const [oneStock, warehouse] = await Promise.all([
      invStockRepository.findOne({
        where: {
          warehouse_id: warehouseCode,
          status: STOCK_STATUS.CLOSED as any,
        },
        order: {
          stock_at: 'DESC',
        },
      }),
      this.warehouseRepository.getWarehouse(warehouseCode),
    ])
    if (!warehouse) {
      throw new Error(
        'No se encontro sucursal con el codigo : ' + warehouseCode,
      )
    }
    const isWarehouse = warehouse.type == WAREHOUSE_TYPE.WAREHOUSE
    return {
      lastClosed: oneStock?.stock_at?.split(' ')[0] ?? null,
      warehouseName: warehouse?.name ?? '',
      isWarehouse,
    }
  }

  async getStockByDate(
    warehouseCode: string,
    date: string,
  ): Promise<{
    stock: StockGeneral[]
    lastClosed: string | null
    warehouseName: string
    isEmpty: boolean
  }> {
    const warehouse = await this.warehouseRepository.getWarehouse(warehouseCode)
    const lastStockClosed = await this.getLastClosedDate(warehouseCode)
    const inventarios = await invStockRepository.find({
      where: {
        warehouse_id: warehouseCode,
        stock_at: Raw((alias) => `DATE(${alias})= :date `, { date }),
        status: In([
          STOCK_STATUS.CLOSED as any,
          STOCK_STATUS.AUTOGENERATED as any,
        ]),
      },
      relations: {
        item: {
          product: {
            category: true,
            measure: true,
          },
          presentation: true,
        },
      },
    })
    const itemsInStock = this.getItemsInStock(inventarios)

    let isClosed = false
    if (lastStockClosed) {
      if (lastStockClosed == date) isClosed = true
      if (lastStockClosed > date) isClosed = true
    }
    const { template, isWarehouse } =
      await this.templateRepository.getDynamicStockTemplate(warehouseCode)

    if (inventarios.length == 0) {
      if (lastStockClosed) {
        return {
          stock: [],
          lastClosed: lastStockClosed,
          warehouseName: warehouse?.name ?? '',
          isEmpty: true,
        }
      } else {
        return {
          stock: this.transformTemplate(template, {
            date,
            warehouse: warehouseCode,
            isWarehouse,
          }),
          lastClosed: lastStockClosed,
          warehouseName: warehouse?.name ?? '',
          isEmpty: true,
        }
      }
    }

    let stockClosed: StockGeneral[] | null = null
    if (!isClosed && lastStockClosed) {
      stockClosed = await this.getLastClosedStock(warehouseCode)
    }

    const allItems = this.unionItems(itemsInStock, template)
    const stock: StockGeneral[] = []
    for (const itemTemplate of allItems) {
      const itemInventario = inventarios.find(
        (el) => el.item_id == itemTemplate.id,
      )
      const beforeInitial = stockClosed?.find(
        (el) => el.itemId == itemTemplate.id,
      )

      const initialStock =
        beforeInitial?.stockPhysical ?? itemInventario?.stock_last ?? 0
      const totalLast =
        beforeInitial?.totalValue ?? itemInventario?.total_value ?? 0

      const quantityInMv = itemInventario?.quantity_in_mv ?? 0
      const quantityOutMv = itemInventario?.quantity_out_mv ?? 0
      const quantityInDispatch = itemInventario?.quantity_in_dp ?? 0
      const quantityOutDispatch = itemInventario?.quantity_out_dp ?? 0
      const quantityInPurchase = itemInventario?.quantity_in_pu ?? 0
      const quantityOutSale = itemInventario?.quantity_out_sl ?? 0

      const stockCurrent = this.calculateCurrent(isWarehouse, {
        initialStock,
        quantityInMv,
        quantityOutMv,
        quantityInDispatch,
        quantityOutDispatch,
        quantityInPurchase,
      })

      stock.push({
        itemId: itemTemplate.id,
        totalInitial: totalLast,
        categoryName: itemTemplate.categoryName,
        itemName: itemTemplate.name,
        presentationId: itemTemplate.presentationId,
        presentationName: itemTemplate.presentationName,
        measureId: itemTemplate.measureId,
        warehouseId: warehouseCode,
        stockAt: date,
        initialStock,
        stockCurrent,
        stockPhysical: itemInventario?.stock_physical ?? 0,
        unitValue: itemInventario
          ? itemInventario.unit_value
          : isWarehouse
            ? itemTemplate.warehousePrice
            : itemTemplate.storePrice,
        totalValue: itemInventario?.total_value ?? 0,
        createdBy: itemInventario?.created_by ?? 'sys',
        status: isClosed ? STOCK_STATUS.CLOSED : STOCK_STATUS.AUTOGENERATED,
        quantityInMv,
        quantityOutMv,
        quantityInDispatch,
        quantityInPurchase,
        quantityOutDispatch,
        quantityOutSale,
      } satisfies StockGeneral)
    }

    return {
      lastClosed: lastStockClosed,
      stock: stock,
      warehouseName: warehouse?.name ?? '',
      isEmpty: false,
    }
  }

  private async stockByDateHelperRange(
    warehouseCode: string,
    date: string,
    { isWarehouse }: { isWarehouse: boolean },
  ): Promise<StockGeneral[]> {
    const inventarios = await invStockRepository.find({
      where: {
        warehouse_id: warehouseCode,
        stock_at: Raw((alias) => `DATE(${alias})= :date `, { date }),
        status: In([
          STOCK_STATUS.CLOSED as any,
          STOCK_STATUS.AUTOGENERATED as any,
        ]),
      },
      relations: {
        item: {
          product: {
            category: true,
            measure: true,
          },
          presentation: true,
        },
      },
    })

    if (inventarios.length == 0) {
      return []
    }
    const itemInStock = this.getItemsInStock(inventarios)
    const allItems = [...itemInStock]
    const stock: StockGeneral[] = []
    for (const itemTemplate of allItems) {
      const itemInventario = inventarios.find(
        (el) => el.item_id == itemTemplate.id,
      )
      const initialStock = itemInventario?.stock_last ?? 0
      const quantityInMv = itemInventario?.quantity_in_mv ?? 0
      const quantityOutMv = itemInventario?.quantity_out_mv ?? 0
      const quantityInDispatch = itemInventario?.quantity_in_dp ?? 0
      const quantityOutDispatch = itemInventario?.quantity_out_dp ?? 0
      const quantityInPurchase = itemInventario?.quantity_in_pu ?? 0
      const quantityOutSale = itemInventario?.quantity_out_sl ?? 0

      const stockCurrent = this.calculateCurrent(isWarehouse, {
        initialStock,
        quantityInMv,
        quantityOutMv,
        quantityInDispatch,
        quantityOutDispatch,
        quantityInPurchase,
      })

      stock.push({
        itemId: itemTemplate.id,
        categoryName: itemTemplate.categoryName,
        itemName: itemTemplate.name,
        presentationId: itemTemplate.presentationId,
        presentationName: itemTemplate.presentationName,
        measureId: itemTemplate.measureId,
        warehouseId: warehouseCode,
        stockAt: date,
        initialStock,
        totalInitial: initialStock > 0 ? (itemInventario?.total_last ?? 0) : 0,
        stockCurrent,
        stockPhysical: itemInventario?.stock_physical ?? 0,
        unitValue: itemInventario
          ? itemInventario.unit_value
          : isWarehouse
            ? itemTemplate.warehousePrice
            : itemTemplate.storePrice,
        totalValue: itemInventario?.total_value ?? 0,
        createdBy: itemInventario?.created_by ?? 'sys',
        status: STOCK_STATUS.AUTOGENERATED,
        quantityInMv,
        quantityOutMv,
        quantityInDispatch,
        quantityInPurchase,
        quantityOutDispatch,
        quantityOutSale,
      } satisfies StockGeneral)
    }

    return stock
  }

  private createDefaultItemRange({
    start,
    end,
    warehouseCode,
    stock,
  }: {
    start: string
    end: string
    warehouseCode: string
    stock: StockGeneral
  }): StockGeneral {
    return {
      ...stock,
      stockAt: `${start} - ${end}`,
      warehouseId: warehouseCode,
      quantityInDispatch: 0,
      quantityInMv: 0,
      quantityInPurchase: 0,
      quantityOutDispatch: 0,
      quantityOutMv: 0,
      quantityOutSale: 0,
      initialStock: 0,
      stockCurrent: 0,
      stockPhysical: 0,
      totalValue: 0,
    } satisfies StockGeneral
  }

  private transformTemplate(
    template: Item[],
    {
      date,
      warehouse,
      isWarehouse,
    }: { date: string; warehouse: string; isWarehouse: boolean },
  ): StockGeneral[] {
    return template.map(
      (el) =>
        ({
          itemId: el.id,
          categoryName: el.categoryName,
          createdBy: 'sys',
          initialStock: 0,
          totalInitial: 0,
          itemName: el.name,
          measureId: el.measureId,
          presentationId: el.presentationId,
          presentationName: el.presentationName,
          quantityInDispatch: 0,
          quantityInMv: 0,
          quantityInPurchase: 0,
          quantityOutDispatch: 0,
          quantityOutMv: 0,
          quantityOutSale: 0,
          status: STOCK_STATUS.AUTOGENERATED,
          stockAt: date,
          stockCurrent: 0,
          stockPhysical: 0,
          totalValue: 0,
          unitValue: isWarehouse ? el.warehousePrice : el.storePrice,
          warehouseId: warehouse,
        }) satisfies StockGeneral,
    )
  }

  private itemToStockGeneral(
    el: Item,
    {
      date,
      warehouse,
      isWarehouse,
    }: { date: string; warehouse: string; isWarehouse: boolean },
  ): StockGeneral {
    return {
      itemId: el.id,
      categoryName: el.categoryName,
      createdBy: 'sys',
      initialStock: 0,
      totalInitial: 0,
      itemName: el.name,
      measureId: el.measureId,
      presentationId: el.presentationId,
      presentationName: el.presentationName,
      quantityInDispatch: 0,
      quantityInMv: 0,
      quantityInPurchase: 0,
      quantityOutDispatch: 0,
      quantityOutMv: 0,
      quantityOutSale: 0,
      status: STOCK_STATUS.AUTOGENERATED,
      stockAt: date,
      stockCurrent: 0,
      stockPhysical: 0,
      totalValue: 0,
      unitValue: isWarehouse ? el.warehousePrice : el.storePrice,
      warehouseId: warehouse,
    }
  }

  private getItemsInStock(inventario: InvStock[]): Item[] {
    const itemInStockDb = inventario.map((el) => el.item)
    const itemsInStock: Item[] = itemInStockDb.map(
      (el) =>
        ({
          id: el.id,
          categoryName: el.product?.category?.category ?? '',
          measureId: el.product?.measureId ?? -1,
          name: el.itemName,
          presentationId: el.presentationId,
          presentationName: el.presentation?.presentation ?? '',
          productId: el.productId,
          storePrice: el.unitPrice,
          warehousePrice: el.unitCost,
        }) satisfies Item,
    )
    return itemsInStock
  }

  private unionItems(items1: Item[], items2: Item[]): Item[] {
    const items = [...items1, ...items2]
    const uniqueItems: Item[] = items.reduce((acc, item) => {
      if (!acc.some((el) => el.id == item.id)) acc.push(item)
      return acc
    }, [] as Item[])

    return uniqueItems
  }

  async getLastClosedDate(warehouseCode: string): Promise<string | null> {
    const inventario = await invStockRepository.findOne({
      where: {
        warehouse_id: warehouseCode,
        status: STOCK_STATUS.CLOSED as any,
      },
      order: {
        stock_at: 'DESC',
      },
    })
    if (!inventario) return null
    return inventario.stock_at.split(' ')[0]
  }

  async getLastClosedStock(
    warehouseCode: string,
  ): Promise<StockGeneral[] | null> {
    const lastStockClosed = await this.getLastClosedDate(warehouseCode)
    if (!lastStockClosed) return null
    const data = await this.getStockByDate(warehouseCode, lastStockClosed)
    return data.stock
  }

  async saveStock(
    stock: StockItemToCreateDto[],
    date: string,
    warehouseCode: string,
  ): Promise<void> {
    const invStock: InvStock[] = []
    if (stock.length == 0) return
    for (const item of stock) {
      const newStock = new InvStock()
      // const current=await this.calculateCurrent()

      newStock.item_id = item.itemId
      newStock.total_last = item.totalInitial
      newStock.item_name = item.itemName
      newStock.total_last = item.totalInitial
      newStock.presentation_id = item.presentationId
      newStock.presentation_name = item.presentationName
      newStock.measure_id = item.measureId
      newStock.warehouse_id = warehouseCode
      newStock.stock_at = date
      newStock.stock_last = item.initialStock
      newStock.stock_current = item.stockCurrent
      newStock.stock_physical = item.stockPhysical
      newStock.unit_value = item.unitValue
      newStock.total_value = item.totalValue
      newStock.created_by = item.createdBy
      newStock.status = item.status as any
      // cantiades
      newStock.quantity_in_mv = item.quantityInMv
      newStock.quantity_out_mv = item.quantityOutMv
      newStock.quantity_in_dp = item.quantityInDispatch
      newStock.quantity_out_dp = item.quantityOutDispatch
      newStock.quantity_in_pu = item.quantityInPurchase
      newStock.quantity_out_sl = item.quantityOutSale
      invStock.push(newStock)
    }

    await AppDataSource.transaction(async (trx) => {
      await trx.query(
        `DELETE FROM inv_stock WHERE warehouse_id = '${warehouseCode}' AND DATE(stock_at) = '${date}'`,
      )
      await trx.insert(InvStock, invStock)
    })
  }

  async saveMultipleStock(
    stock: StockItemToCreateDto[],
    date: string,
    warehouses: string[],
  ): Promise<void> {
    const invStock: InvStock[] = []
    if (stock.length == 0) return
    if (warehouses.length == 0)
      throw new Error('No se puede guardar un stock con sucursales vacías')
    for (const item of stock) {
      const newStock = new InvStock()
      newStock.item_id = item.itemId
      newStock.total_last = item.totalInitial
      newStock.item_name = item.itemName
      newStock.presentation_id = item.presentationId
      newStock.presentation_name = item.presentationName
      newStock.measure_id = item.measureId
      newStock.warehouse_id = item.warehouseId
      newStock.stock_at = date
      newStock.stock_last = item.initialStock
      newStock.stock_current = item.stockCurrent
      newStock.stock_physical = item.stockPhysical
      newStock.unit_value = item.unitValue
      newStock.total_value = item.totalValue
      newStock.created_by = item.createdBy
      newStock.status = item.status as any
      // cantidades
      newStock.quantity_in_mv = item.quantityInMv
      newStock.quantity_out_mv = item.quantityOutMv
      newStock.quantity_in_dp = item.quantityInDispatch
      newStock.quantity_out_dp = item.quantityOutDispatch
      newStock.quantity_in_pu = item.quantityInPurchase
      newStock.quantity_out_sl = item.quantityOutSale

      invStock.push(newStock)
    }
    await AppDataSource.transaction(async (trx) => {
      await trx.query(
        `DELETE FROM inv_stock WHERE warehouse_id IN ('${warehouses.join(
          "','",
        )}') AND DATE(stock_at) = '${date}'`,
      )

      await trx.insert(InvStock, invStock)
    })
  }

  getInvStockFromStockCreate(
    stock: StockItemToCreateDto[],
    date: string,
  ): InvStock[] {
    const invStock: InvStock[] = []
    for (const item of stock) {
      const newStock = new InvStock()
      newStock.item_id = item.itemId
      newStock.total_last = item.totalInitial
      newStock.item_name = item.itemName
      newStock.presentation_id = item.presentationId
      newStock.presentation_name = item.presentationName
      newStock.measure_id = item.measureId
      newStock.warehouse_id = item.warehouseId
      newStock.stock_at = date
      newStock.stock_last = item.initialStock
      newStock.stock_current = item.stockCurrent
      newStock.stock_physical = item.stockPhysical
      newStock.unit_value = item.unitValue
      newStock.total_value = item.totalValue
      newStock.created_by = item.createdBy
      newStock.status = item.status as any
      // cantidades
      newStock.quantity_in_mv = item.quantityInMv
      newStock.quantity_out_mv = item.quantityOutMv
      newStock.quantity_in_dp = item.quantityInDispatch
      newStock.quantity_out_dp = item.quantityOutDispatch
      newStock.quantity_in_pu = item.quantityInPurchase
      newStock.quantity_out_sl = item.quantityOutSale

      invStock.push(newStock)
    }
    return invStock
  }

  async getRangeStock(
    warehouseCode: string,
    start: string,
    end: string,
  ): Promise<{
    stock: StockGeneral[]
    lastClosed: string | null
    warehouseName: string
  }> {
    const dates = eachDayOfInterval({
      start: parseISO(start),
      end: parseISO(end),
    }).map((el) => format(el, 'yyyy-MM-dd'))
    const warehouse = await this.warehouseRepository.getWarehouse(warehouseCode)
    if (!warehouse)
      throw new Error(
        'No se encontro sucursal con el codigo : ' + warehouseCode,
      )
    const isWarehouse = warehouse.type == WAREHOUSE_TYPE.WAREHOUSE
    const lastDateClosed = await this.getLastClosedDate(warehouseCode)
    const template = await this.templateRepository.getItemsTemplate(isWarehouse)
    const stocksDbPromises = [] as Promise<StockGeneral[]>[]

    for (const date of dates) {
      stocksDbPromises.push(
        this.stockByDateHelperRange(warehouseCode, date, {
          isWarehouse,
        }),
      )
    }
    const stocksByDate = await Promise.all(stocksDbPromises)
    // const allStocks = stocksByDate.flat()

    const stock: { [key: string]: StockGeneral } = {}

    for (let i = 0; i < stocksByDate.length; i++) {
      const stockByDate = stocksByDate[i]
      for (const stockDB of stockByDate) {
        if (!stockDB) continue
        if (!stock[stockDB.itemId]) {
          stock[stockDB.itemId] = this.createDefaultItemRange({
            start,
            end,
            warehouseCode,
            stock: stockDB,
          })
        }
        stock[stockDB.itemId].quantityInDispatch += stockDB.quantityInDispatch
        stock[stockDB.itemId].quantityOutDispatch += stockDB.quantityOutDispatch
        stock[stockDB.itemId].quantityInPurchase += stockDB.quantityInPurchase
        stock[stockDB.itemId].quantityOutSale += stockDB.quantityOutSale
        stock[stockDB.itemId].quantityInMv += stockDB.quantityInMv
        stock[stockDB.itemId].quantityOutMv += stockDB.quantityOutMv

        if (i == 0) {
          stock[stockDB.itemId].initialStock = stockDB.initialStock
          stock[stockDB.itemId].totalInitial = stockDB.totalInitial
        }
        if (i == stocksByDate.length - 1) {
          stock[stockDB.itemId].stockPhysical = stockDB.stockPhysical
          stock[stockDB.itemId].totalValue = stockDB.totalValue
          stock[stockDB.itemId].stockCurrent = this.calculateCurrent(
            isWarehouse,
            {
              ...stock[stockDB.itemId],
            },
          )
        }
      }
    }
    for (const itemTemplate of template) {
      if (!stock[itemTemplate.id]) {
        stock[itemTemplate.id] = this.itemToStockGeneral(itemTemplate, {
          date: `${start} - ${end}`,
          isWarehouse,
          warehouse: warehouseCode,
        })
      }
    }
    const allItems = Object.values(stock).sort((a, b) =>
      a.itemName.localeCompare(b.itemName),
    )

    return {
      stock: allItems,
      lastClosed: lastDateClosed,
      warehouseName: warehouse?.name ?? '',
    }
  }

  async rangeStockByDate({
    warehouseCode,
    start,
    end,
  }: {
    warehouseCode: string
    start: string
    end: string
  }): Promise<StockGeneral[][]> {
    const dates = eachDayOfInterval({
      start: parseISO(start),
      end: parseISO(end),
    }).map((el) => format(el, 'yyyy-MM-dd'))
    const warehouse = await this.warehouseRepository.getWarehouse(warehouseCode)
    if (!warehouse)
      throw new Error(
        'No se encontro sucursal con el codigo : ' + warehouseCode,
      )
    const isWarehouse = warehouse.type == WAREHOUSE_TYPE.WAREHOUSE
    const stocksDbPromises = [] as Promise<StockGeneral[]>[]

    for (const date of dates) {
      stocksDbPromises.push(
        this.stockByDateHelperRange(warehouseCode, date, {
          isWarehouse,
        }),
      )
    }
    const stocksByDate = await Promise.all(stocksDbPromises)
    return stocksByDate
  }

  async getAdvancedRangeStock({
    type,
    start,
    end,
  }: {
    type?: WAREHOUSE_TYPE
    start: string
    end: string
  }): Promise<StockGeneral[]> {
    let warehouses = await this.warehouseRepository.getWarehouses()
    if (type) {
      warehouses = warehouses.filter((el) => el.type == type)
    }
    if (warehouses.length == 0) return []

    const warehouseSql = warehouses.map((el) => `'${el.code}'`).join(',')
    const [initial, last]: [InitialStockDb[], LastStockDb[]] =
      await Promise.all([
        AppDataSource.query(
          `SELECT item_id,stock_last,total_last FROM inv_stock is2 WHERE is2.warehouse_id IN (${warehouseSql}) AND DATE(stock_at)="${start}" GROUP BY item_id;`,
        ),
        AppDataSource.query(
          `SELECT item_id,stock_physical,unit_value,total_value FROM inv_stock is2 WHERE is2.warehouse_id IN (${warehouseSql}) AND DATE(stock_at)="${end}" GROUP BY item_id;`,
        ),
      ])

    const rows: StockRowAllDb[] =
      await AppDataSource.query(`SELECT is2.item_id, is2.item_name,SUM(is2.quantity_in_mv) quantity_in_mv, SUM(is2.quantity_out_mv) quantity_out_mv ,SUM(is2.quantity_out_dp) quantity_out_dp ,SUM(is2.quantity_in_dp) quantity_in_dp,
SUM(is2.quantity_in_pu) quantity_in_pu,SUM(is2.quantity_out_sl) quantity_out_sl,unit_value FROM inv_stock is2
WHERE is2.warehouse_id IN (${warehouseSql}) AND stock_at BETWEEN "${start}" AND "${end}"
GROUP BY item_id;`)

    if (rows.length == 0 && initial.length == 0 && last.length == 0) return []
    const initialItemIds = initial.map((el) => el.item_id)
    const lastItemIds = last.map((el) => el.item_id)
    const rowsItemIds = rows.map((el) => el.item_id)
    const allItemIds = [...initialItemIds, ...lastItemIds, ...rowsItemIds]
    const uniqueItemIds = [...new Set(allItemIds)]
    const stock: StockGeneral[] = []

    const items = await productItemRepository.find({
      where: { id: In(uniqueItemIds) },
      relations: {
        product: {
          category: true,
        },
        presentation: true,
      },
    })
    for (const itemId of uniqueItemIds) {
      const itemDb = items.find((el) => el.id == itemId)
      const intialItem = initial.find((el) => el.item_id == itemId)
      const lastItem = last.find((el) => el.item_id == itemId)

      const row = rows.find((el) => el.item_id == itemId)

      let quantityInMv = 0
      let quantityOutMv = 0
      let quantityInDispatch = 0
      let quantityOutDispatch = 0
      let quantityInPurchase = 0
      let quantityOutSale = 0

      let initialStock = 0
      let totalInitial = 0
      let stockPhysical = 0
      let totalValue = 0
      if (row) {
        quantityInMv = Number(row.quantity_in_mv)
        quantityOutMv = Number(row.quantity_out_mv)
        quantityOutDispatch = Number(row.quantity_out_dp)
        quantityInDispatch = Number(row.quantity_in_dp)
        quantityInPurchase = Number(row.quantity_in_pu)
        quantityOutSale = Number(row.quantity_out_sl)
      }
      const unitValue = row?.unit_value ?? lastItem?.unit_value ?? 0

      if (lastItem) {
        // stockPhysical = Number(lastItem.stock_physical)
        // totalValue = Number(lastItem.total_value)
        // unitValue = Number(lastStock.unit_value)
        stockPhysical = Number(lastItem.stock_physical)
        totalValue = Number(lastItem.total_value)
      }
      if (intialItem) {
        // initialStock = Number(intialItem.stock_last)
        // current = initialStock + current
        initialStock = Number(intialItem.stock_last)
        totalInitial = Number(intialItem.total_last)
      }
      // const current=this.calculateCurrent(type==)
      // const current =
      //   quantityInMv +
      //   quantityInDispatch +
      //   quantityInPurchase -
      //   (quantityOutMv + quantityOutDispatch + quantityOutSale)
      let current = 0
      if (!type) {
        current =
          quantityInMv +
          quantityInDispatch +
          quantityInPurchase -
          (quantityOutMv + quantityOutDispatch + quantityOutSale)
      } else if (type == WAREHOUSE_TYPE.STORE) {
        current = calculateCurrent(false, {
          initialStock: initialStock,
          quantityInDispatch: quantityInDispatch,
          quantityInMv: quantityInMv,
          quantityInPurchase: quantityInPurchase,
          quantityOutDispatch: quantityOutDispatch,
          quantityOutMv: quantityOutMv,
        })
      } else if (type == WAREHOUSE_TYPE.WAREHOUSE) {
        current = calculateCurrent(true, {
          initialStock: initialStock,
          quantityInDispatch: quantityInDispatch,
          quantityInMv: quantityInMv,
          quantityInPurchase: quantityInPurchase,
          quantityOutDispatch: quantityOutDispatch,
          quantityOutMv: quantityOutMv,
        })
      }

      stock.push({
        itemId: itemId,
        categoryName: itemDb?.product?.category?.category ?? '',
        createdBy: 'sys',
        itemName: itemDb?.itemName ?? '',
        initialStock,
        totalInitial,
        measureId: itemDb?.product?.measureId ?? 0,
        presentationId: itemDb?.presentationId ?? 0,
        presentationName: itemDb?.presentation?.presentation ?? '',
        totalValue,
        unitValue: Number(unitValue),
        status: STOCK_STATUS.AUTOGENERATED,
        warehouseId: '',
        stockAt: `${start} - ${end}`,
        stockCurrent: current,
        stockPhysical,
        quantityInDispatch,
        quantityInMv,
        quantityInPurchase,
        quantityOutDispatch,
        quantityOutMv,
        quantityOutSale,
      })
    }

    return stock
  }

  async getFinalValueStock(
    warehouseCode: string,
    date: string,
  ): Promise<number> {
    const stock = await this.stockRepository.find({
      where: {
        warehouse_id: warehouseCode,
        stock_at: Raw((alias) => `DATE(${alias}) = '${date}'`),
        status: STOCK_STATUS.CLOSED as any,
      },
    })
    return stock.reduce((acc, el) => acc + Number(el.total_value), 0)
  }
  async hasBeforeStock(warehouseId: string, date: string): Promise<boolean> {
    const oneStock = await this.stockRepository.findOne({
      select: { id: true },
      where: {
        warehouse_id: warehouseId,
        stock_at: Raw((alias) => `DATE(${alias}) < '${date}'`),
        status: STOCK_STATUS.CLOSED as any,
      },
    })
    return !!oneStock
  }
}

interface InitialStockDb {
  item_id: number
  total_last: string
  stock_last: string
}

interface LastStockDb {
  item_id: number
  stock_physical: string
  unit_value: string
  total_value: string
}

interface StockRowDb {
  item_id: number
  item_name: string
  quantity_in_mv: string
  quantity_out_mv: string
  quantity_out_dp: string
  quantity_in_dp: string
  quantity_in_pu: string
  quantity_out_sl: string
}

interface StockRowAllDb extends StockRowDb {
  unit_value: string
}
