export enum STOCK_STATUS {
  AUTOGENERATED = 1,
  CLOSED = 2,
}

export interface Stock {
  id: number
  itemId: number
  itemName: string
  categoryName: string
  presentationId: number
  presentationName: string
  measureId: number
  warehouseId: string
  stockAt: string
  initialStock: number
  stockCurrent: number
  stockPhysical: number
  unitValue: number
  totalValue: number
  createdBy: string
  status: STOCK_STATUS
  // agregados - modificados
  quantityInMv: number
  quantityInPurchase: number
  quantityInDispatch: number
  quantityOutMv: number
  quantityOutDispatch: number
  quantityOutSale: number
}

export interface StockGeneral extends Omit<Stock, 'id'> {
  id?: number
}

export enum DISPATCH_MOVE_TYPE {
  WAREHOUSE_TO_STORE = 'D',
  STORE_TO_STORE = 'M',
  EXCEPTIONAL = 'E',
}
export enum DISPATCH_STATUS {
  NEW = 1,
  APPROVED = 2,
  DISPATCHED = 3,
  CANCELLED = 0,
  INVOICED = 4,
}

export interface Dispatch {
  id: number
  wareToId: string
  wareFromId: string
  dispatchAt: string
  wareToName: string
  wareFromName: string
  numInvoice: string
  numGuide: string
  taxValue: number
  gloss: string
  moveType: DISPATCH_MOVE_TYPE
  netValue: number
  totalValue: number
  status: DISPATCH_STATUS
  requestBy: string
  approvedBy: string
  items: DispatchItem[]
}
export interface DispatchRoute extends Omit<Dispatch, 'items'> {
  route: string
  items: DispatchRouteItem[]
}

export interface DispatchRouteItem extends DispatchItem {
  categoryId: number
  categoryName: string
}

export interface DispatchItem {
  id: number
  dispatchId: number
  itemId: number
  itemName: string
  presentationId: number
  presentationName: string
  measureId: number
  measureCode: string
  quantity: number
  unitValue: number
  totalValue: number
}

export interface StockItemToCreateDto extends Omit<Stock, 'id'> {}

export interface DispatchItemAddDto
  extends Omit<DispatchItem, 'id' | 'measureCode'> {
  id?: number
}
export interface DispatchUpdateDto extends Omit<Dispatch, 'items'> {
  items: DispatchItemAddDto[]
}
export enum WAREHOUSE_TYPE {
  WAREHOUSE = 'W',
  STORE = 'T',
}

export interface Warehouse {
  code: string
  name: string
  type: WAREHOUSE_TYPE | null
}

export interface WarehouseLegal extends Warehouse {
  legalName: string
  legalAddress: string
  legalNumber: string
  serie: string
  correlativo: number
  guideSerie: string
  guideCorrelativo: number
  district: string
}

export interface StockItemToCreateDto extends Omit<Stock, 'id'> {}

export enum PURCHASE_STATUS {
  NEW = 1,
  STORED = 3,
}

export interface Purchase {
  id: number
  gloss: string
  items: PurchaseItem[]
  supplierId: number
  supplierName: string
  purchaseAt: string
  status: PURCHASE_STATUS
  numInvoice: string
  numGuide: string
  warehouseId: string
  discount: number
  taxValue: number | null
}

export interface PurchaseItem {
  id: number
  purchaseId: number
  itemId: number
  itemName: string
  presentationId: number
  presentationName: string
  unitValue: number
  quantity: number
  totalValue: number
}

export interface PurchaseItemUpdate
  extends Omit<PurchaseItem, 'id' | 'itemId'> {
  id: undefined | number
  itemId: undefined | number
  key: number
}

export interface PurchaseUpdaetDto extends Omit<Purchase, 'items'> {
  supplierName: string
  supplierRuc?: string
  items: PurchaseItemUpdate[]
}

export interface Item {
  id: number
  categoryName: string
  name: string
  productId: number
  warehousePrice: number
  storePrice: number
  measureId: number
  presentationId: number
  presentationName: string
}

export interface MoveItemDto {
  itemId: number
  quantity: number
}

export interface MoveBetweenStoresDto {
  storeToId: string
  storeFrom: string
  moveAt: string
  gloss: string
  items: MoveItemDto[]
}

export interface DispatchItemCreateDto
  extends Omit<DispatchItem, 'id' | 'measureCode'> {
  id?: number
}

export interface DispatchCreateDto
  extends Omit<Dispatch, 'items' | 'id' | 'wareFromName' | 'wareToName'> {
  items: DispatchItemCreateDto[]
}

export interface DispatchTransport {
  transportCompanyName: string
  licensePlateNumber: string
  driverDocumentType: string
  driverDocumentNumber: string
  driverFirstName: string
  driverLastName: string
  driverLicenseNumber: string
}

export interface Driver {
  id: number

  transportName: string

  transportCompanyName: string

  transportPlateNumber: string

  driverTypeDoc: string

  driverDocNumber: string

  driverFirstName: string

  driverLastName: string

  driverLicenseNumber: string

  status: string
}

export interface CreateDriverDto {
  transportName: string
  transportCompanyName: string
  transportPlateNumber: string
  carrierDocNumber: string
  driverTypeDoc: string
  driverDocNumber: string
  driverFirstName: string
  driverLastName: string
  driverLicenseNumber: string
  status: string
}

export interface UpdateDriverDto extends Partial<CreateDriverDto> {
  id: number
}

export interface WarehouseRoute extends Warehouse {
  route: string
}

export interface DispatchSummary {
  categoryId: number
  categoryName: string
  itemId: number
  itemName: string
  dates: {
    [date: string]: number
  }
}
